import type { RawPublication } from "@/lib/types";
import { p } from "../_pub";

const CHECKED = "2026-06-13";

/**
 * Batch 1: real external journals, reports, and institutional publications
 * relevant to nature, conservation, ecology, geology, and Indonesia. Each item is
 * a real external publication with a traceable URL. The synopsis is NaLI's
 * Indonesian summary OF the publication, not a NaLI-authored article.
 */
export const publicationsBatch1: RawPublication[] = [
  p({
    slug: "oryx-cambridge",
    title: "Oryx, The International Journal of Conservation",
    publicationType: "journal",
    publisherOrInstitution: "Cambridge University Press (Fauna & Flora International)",
    sourceUrl: "https://www.cambridge.org/core/journals/oryx",
    language: "en",
    accessType: "free_to_read",
    synopsis:
      "Jurnal konservasi internasional yang diterbitkan untuk Fauna & Flora International. Memuat riset dan kebijakan tentang spesies terancam, kawasan lindung, dan upaya pemulihan. Beberapa artikelnya, termasuk pembahasan klaim keberadaan harimau Jawa, menjadi rujukan penting bagi pembaca Indonesia.",
    whyItMatters:
      "Salah satu jurnal konservasi paling dihormati, sering memuat studi yang relevan dengan satwa dan kawasan di Indonesia, dengan standar bukti yang jelas.",
    topics: ["konservasi", "spesies terancam", "kebijakan"],
    geography: ["Global", "Indonesia"],
    relatedSourceIds: ["harimau-jawa-oryx-2024", "harimau-jawa-oryx-rebuttal-2024"],
    relatedArticleIds: ["harimau-jawa-lazarus-species"],
    limitations: ["Sebagian artikel berbayar; baca abstrak terbuka atau cari versi terbuka penulis."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "biological-conservation-elsevier",
    title: "Biological Conservation",
    publicationType: "journal",
    publisherOrInstitution: "Elsevier (ScienceDirect)",
    sourceUrl: "https://www.sciencedirect.com/journal/biological-conservation",
    language: "en",
    accessType: "paywalled",
    synopsis:
      "Jurnal ilmiah yang memuat riset tentang pelestarian keanekaragaman hayati, dari ekologi populasi sampai dampak perubahan lahan. Banyak studi tentang hutan tropis dan satwa Asia Tenggara terbit di sini.",
    whyItMatters:
      "Rujukan inti untuk metode dan temuan konservasi; berguna ketika menelusuri tekanan terhadap spesies dan habitat di Indonesia.",
    topics: ["konservasi", "biodiversitas", "ekologi"],
    geography: ["Global"],
    relatedSourceIds: [],
    limitations: ["Mayoritas artikel berbayar; sebagian tersedia sebagai pracetak atau versi terbuka."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "conservation-biology-wiley",
    title: "Conservation Biology",
    publicationType: "journal",
    publisherOrInstitution: "Wiley (Society for Conservation Biology)",
    sourceUrl: "https://conbio.onlinelibrary.wiley.com/journal/15231739",
    language: "en",
    accessType: "paywalled",
    synopsis:
      "Jurnal resmi Society for Conservation Biology, memuat riset dan teori konservasi dari skala gen sampai bentang alam. Menjadi salah satu tempat utama perdebatan metode dan prioritas pelestarian.",
    whyItMatters:
      "Membantu memahami kerangka berpikir konservasi modern yang sering dipakai dalam laporan dan kebijakan tentang kawasan Indonesia.",
    topics: ["konservasi", "biodiversitas", "kebijakan"],
    geography: ["Global"],
    relatedSourceIds: [],
    limitations: ["Sebagian besar artikel berbayar."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "journal-for-nature-conservation",
    title: "Journal for Nature Conservation",
    publicationType: "journal",
    publisherOrInstitution: "Elsevier (ScienceDirect)",
    sourceUrl: "https://www.sciencedirect.com/journal/journal-for-nature-conservation",
    language: "en",
    accessType: "paywalled",
    synopsis:
      "Jurnal yang memuat riset konservasi alam, metode pengelolaan habitat, dan hubungan antara biodiversitas dengan kebijakan. Cocok sebagai pintu masuk ke studi konservasi terapan.",
    whyItMatters:
      "Berguna ketika membaca tekanan terhadap spesies, kawasan lindung, dan restorasi ekosistem, termasuk konteks Indonesia.",
    topics: ["konservasi", "pengelolaan habitat", "restorasi"],
    geography: ["Global"],
    relatedSourceIds: [],
    limitations: ["Sebagian artikel berbayar."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "global-ecology-and-conservation",
    title: "Global Ecology and Conservation",
    publicationType: "journal",
    publisherOrInstitution: "Elsevier (ScienceDirect)",
    sourceUrl: "https://www.sciencedirect.com/journal/global-ecology-and-conservation",
    language: "en",
    accessType: "open_access",
    synopsis:
      "Jurnal akses terbuka yang memuat riset ekologi dan konservasi dari seluruh dunia, termasuk banyak studi lapangan di kawasan tropis. Karena terbuka, artikelnya dapat dibaca penuh tanpa berlangganan.",
    whyItMatters:
      "Akses terbuka membuatnya praktis untuk menelusuri studi konservasi Indonesia tanpa hambatan biaya.",
    topics: ["ekologi", "konservasi", "akses terbuka"],
    geography: ["Global", "Indonesia"],
    relatedSourceIds: [],
    limitations: ["Cakupan luas; relevansi tiap artikel perlu dinilai per topik."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "biodiversity-and-conservation-springer",
    title: "Biodiversity and Conservation",
    publicationType: "journal",
    publisherOrInstitution: "Springer Nature",
    sourceUrl: "https://link.springer.com/journal/10531",
    language: "en",
    accessType: "paywalled",
    synopsis:
      "Jurnal yang fokus pada keanekaragaman hayati dan pelestariannya, dari hutan tropis sampai laut. Memuat studi sebaran spesies, endemisme, dan tekanan habitat.",
    whyItMatters:
      "Indonesia sebagai negara megabiodiversitas sering muncul dalam studi yang diterbitkan di sini.",
    topics: ["biodiversitas", "konservasi", "endemisme"],
    geography: ["Global", "Indonesia"],
    relatedSourceIds: [],
    limitations: ["Sebagian besar artikel berbayar."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "zookeys-pensoft",
    title: "ZooKeys",
    publicationType: "journal",
    publisherOrInstitution: "Pensoft Publishers",
    sourceUrl: "https://zookeys.pensoft.net",
    language: "en",
    accessType: "open_access",
    synopsis:
      "Jurnal zoologi akses terbuka yang banyak memuat deskripsi spesies baru dan revisi taksonomi. Banyak jenis serangga, moluska, dan vertebrata dari Asia Tenggara dipublikasikan pertama kali di sini.",
    whyItMatters:
      "Penemuan dan penamaan spesies baru Indonesia sering melewati ZooKeys; aksesnya terbuka penuh.",
    topics: ["taksonomi", "zoologi", "spesies baru"],
    geography: ["Global", "Indonesia"],
    relatedSourceIds: [],
    limitations: ["Fokus taksonomi; tidak semua artikel membahas konservasi."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "nature-conservation-pensoft",
    title: "Nature Conservation",
    publicationType: "journal",
    publisherOrInstitution: "Pensoft Publishers",
    sourceUrl: "https://natureconservation.pensoft.net",
    language: "en",
    accessType: "open_access",
    synopsis:
      "Jurnal akses terbuka yang memuat riset dan kebijakan konservasi, termasuk pengelolaan kawasan lindung dan jejaring ekologi. Terbuka penuh untuk dibaca.",
    whyItMatters:
      "Sumber terbuka untuk studi konservasi terapan yang dapat diakses tanpa berlangganan.",
    topics: ["konservasi", "kawasan lindung", "kebijakan"],
    geography: ["Global"],
    relatedSourceIds: [],
    limitations: ["Volume terbitan lebih kecil dibanding jurnal besar."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "raffles-bulletin-of-zoology",
    title: "The Raffles Bulletin of Zoology",
    publicationType: "journal",
    publisherOrInstitution: "Lee Kong Chian Natural History Museum, National University of Singapore",
    sourceUrl: "https://lkcnhm.nus.edu.sg/publications/raffles-bulletin-of-zoology/",
    language: "en",
    accessType: "open_access",
    synopsis:
      "Jurnal zoologi akses terbuka yang menjadi rujukan klasik untuk fauna Asia Tenggara, termasuk Indonesia. Banyak deskripsi dan catatan sebaran satwa kawasan ini tersimpan di arsipnya.",
    whyItMatters:
      "Salah satu arsip zoologi regional terpenting untuk fauna Nusantara, dengan akses terbuka.",
    topics: ["zoologi", "fauna", "Asia Tenggara"],
    geography: ["Asia Tenggara", "Indonesia"],
    relatedSourceIds: [],
    limitations: ["Berorientasi taksonomi dan sistematika."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "treubia-brin",
    title: "Treubia, A Journal on Zoology of the Indo-Australian Archipelago",
    publicationType: "journal",
    publisherOrInstitution: "Badan Riset dan Inovasi Nasional (BRIN), Indonesia",
    sourceUrl: "https://e-journal.brin.go.id/treubia",
    language: "en",
    accessType: "open_access",
    synopsis:
      "Jurnal zoologi tua Indonesia yang fokus pada fauna kepulauan Indo-Australia. Diterbitkan lembaga riset nasional, ia memuat studi satwa Nusantara dan menjadi bagian dari sejarah ilmu hayati Indonesia.",
    whyItMatters:
      "Jurnal nasional dengan warisan panjang tentang fauna Indonesia, kini terbuka secara daring.",
    topics: ["zoologi", "fauna", "Indonesia"],
    geography: ["Indonesia"],
    relatedSourceIds: [],
    limitations: ["Frekuensi terbit terbatas; alamat daring dapat berpindah seiring migrasi portal BRIN."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "reinwardtia-brin",
    title: "Reinwardtia, A Journal on Taxonomic Botany",
    publicationType: "journal",
    publisherOrInstitution: "Badan Riset dan Inovasi Nasional (BRIN), Indonesia",
    sourceUrl: "https://e-journal.brin.go.id/reinwardtia",
    language: "en",
    accessType: "open_access",
    synopsis:
      "Jurnal botani sistematika Indonesia yang memuat deskripsi dan revisi tumbuhan, terutama flora Malesia. Menjadi rujukan untuk keanekaragaman tumbuhan Nusantara.",
    whyItMatters:
      "Salah satu jurnal botani nasional utama untuk flora Indonesia, dengan akses terbuka.",
    topics: ["botani", "taksonomi", "flora"],
    geography: ["Indonesia", "Malesia"],
    relatedSourceIds: [],
    limitations: ["Fokus taksonomi tumbuhan; alamat portal dapat berubah."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "berita-biologi-brin",
    title: "Berita Biologi, Jurnal Ilmu-ilmu Hayati",
    publicationType: "journal",
    publisherOrInstitution: "Badan Riset dan Inovasi Nasional (BRIN), Indonesia",
    sourceUrl: "https://e-journal.brin.go.id/berita_biologi",
    language: "id",
    accessType: "open_access",
    synopsis:
      "Jurnal ilmu hayati berbahasa Indonesia dan Inggris yang memuat riset biologi, termasuk botani, zoologi, dan mikrobiologi dari peneliti dalam negeri. Banyak studi lokal yang sulit ditemukan di jurnal internasional terbit di sini.",
    whyItMatters:
      "Jurnal nasional berbahasa Indonesia yang dekat dengan riset hayati lokal dan terbuka untuk dibaca.",
    topics: ["biologi", "hayati", "Indonesia"],
    geography: ["Indonesia"],
    relatedSourceIds: [],
    limitations: ["Cakupan luas; relevansi per artikel perlu dinilai."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "biodiversitas-smujo",
    title: "Biodiversitas, Journal of Biological Diversity",
    publicationType: "journal",
    publisherOrInstitution: "Universitas Sebelas Maret (Smujo), Indonesia",
    sourceUrl: "https://smujo.id/biodiv",
    language: "en",
    accessType: "open_access",
    synopsis:
      "Jurnal keanekaragaman hayati akses terbuka asal Indonesia yang banyak memuat studi spesies, ekosistem, dan etnobiologi Nusantara. Salah satu jurnal Indonesia dengan jangkauan internasional.",
    whyItMatters:
      "Wadah besar untuk riset biodiversitas Indonesia yang dapat diakses penuh tanpa biaya.",
    topics: ["biodiversitas", "ekologi", "Indonesia"],
    geography: ["Indonesia"],
    relatedSourceIds: [],
    limitations: ["Volume besar; mutu antar artikel bervariasi dan perlu dinilai per kasus."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "coral-reefs-springer",
    title: "Coral Reefs, Journal of the International Coral Reef Society",
    publicationType: "journal",
    publisherOrInstitution: "Springer Nature",
    sourceUrl: "https://link.springer.com/journal/338",
    language: "en",
    accessType: "paywalled",
    synopsis:
      "Jurnal khusus terumbu karang yang memuat riset biologi, ekologi, dan respons karang terhadap pemanasan laut. Kawasan Segitiga Terumbu Karang, termasuk Indonesia, sering menjadi lokasi studinya.",
    whyItMatters:
      "Rujukan utama untuk memahami pemutihan karang dan kesehatan terumbu, isu penting bagi laut Indonesia.",
    topics: ["terumbu karang", "laut", "iklim"],
    geography: ["Global", "Indonesia"],
    relatedSourceIds: ["noaa-coral-reef-watch", "ipcc-srocc-coral-reefs"],
    limitations: ["Sebagian besar artikel berbayar."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "marine-pollution-bulletin",
    title: "Marine Pollution Bulletin",
    publicationType: "journal",
    publisherOrInstitution: "Elsevier (ScienceDirect)",
    sourceUrl: "https://www.sciencedirect.com/journal/marine-pollution-bulletin",
    language: "en",
    accessType: "paywalled",
    synopsis:
      "Jurnal tentang pencemaran laut, termasuk sampah plastik, tumpahan, dan dampak limbah pada ekosistem pesisir. Banyak studi tentang plastik laut Asia Tenggara terbit di sini.",
    whyItMatters:
      "Relevan untuk isu sampah plastik laut Indonesia yang sering dibahas dengan data dari jurnal ini.",
    topics: ["pencemaran laut", "plastik", "pesisir"],
    geography: ["Global", "Indonesia"],
    relatedSourceIds: ["jambeck-plastic-waste-science-2015"],
    limitations: ["Sebagian besar artikel berbayar."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "plos-one",
    title: "PLOS ONE",
    publicationType: "journal",
    publisherOrInstitution: "Public Library of Science (PLOS)",
    sourceUrl: "https://journals.plos.org/plosone/",
    language: "en",
    accessType: "open_access",
    synopsis:
      "Jurnal akses terbuka multidisiplin yang memuat riset dari banyak bidang, termasuk ekologi, konservasi, dan ilmu kebumian. Karena terbuka penuh dan bervolume besar, banyak studi tentang Indonesia dapat ditemukan di sini.",
    whyItMatters:
      "Akses terbuka penuh menjadikannya sumber praktis untuk studi yang sering dirujuk media dan laporan.",
    topics: ["multidisiplin", "ekologi", "akses terbuka"],
    geography: ["Global", "Indonesia"],
    relatedSourceIds: [],
    limitations: ["Volume sangat besar; relevansi dan mutu perlu dinilai per artikel."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "nhess-copernicus",
    title: "Natural Hazards and Earth System Sciences (NHESS)",
    publicationType: "journal",
    publisherOrInstitution: "Copernicus Publications (EGU)",
    sourceUrl: "https://nhess.copernicus.org",
    language: "en",
    accessType: "open_access",
    synopsis:
      "Jurnal akses terbuka tentang bahaya alam dan sistem kebumian, termasuk tsunami, letusan, longsor, dan banjir. Studi tentang tsunami Selat Sunda 2018 dan bahaya vulkanik Indonesia terbit di sini.",
    whyItMatters:
      "Sumber terbuka penting untuk memahami bahaya geologi Indonesia seperti tsunami dan letusan.",
    topics: ["bahaya alam", "tsunami", "geologi"],
    geography: ["Global", "Indonesia"],
    relatedSourceIds: ["nhess-anak-krakatau-2018"],
    relatedArticleIds: ["anak-krakatau-2018-runtuhan-tsunami"],
    limitations: ["Berorientasi ilmu kebumian teknis."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "jvgr-elsevier",
    title: "Journal of Volcanology and Geothermal Research",
    publicationType: "journal",
    publisherOrInstitution: "Elsevier (ScienceDirect)",
    sourceUrl: "https://www.sciencedirect.com/journal/journal-of-volcanology-and-geothermal-research",
    language: "en",
    accessType: "paywalled",
    synopsis:
      "Jurnal khusus vulkanologi dan panas bumi yang memuat riset tentang letusan, kawah, dan sistem magma. Gunung-gunung api Indonesia, dari Merapi sampai Tambora, kerap menjadi objek studinya.",
    whyItMatters:
      "Rujukan inti untuk memahami perilaku gunung api Indonesia secara ilmiah.",
    topics: ["vulkanologi", "gunung api", "geologi"],
    geography: ["Global", "Indonesia"],
    relatedSourceIds: ["tambora-oppenheimer-2003"],
    limitations: ["Sebagian besar artikel berbayar."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "bulletin-of-volcanology-springer",
    title: "Bulletin of Volcanology",
    publicationType: "journal",
    publisherOrInstitution: "Springer Nature (IAVCEI)",
    sourceUrl: "https://link.springer.com/journal/445",
    language: "en",
    accessType: "paywalled",
    synopsis:
      "Jurnal resmi asosiasi vulkanologi internasional yang memuat riset tentang proses letusan, bahaya, dan pemantauan gunung api. Banyak studi kasus gunung api Indonesia muncul di sini.",
    whyItMatters:
      "Melengkapi pemahaman ilmiah tentang bahaya dan pemantauan gunung api di Nusantara.",
    topics: ["vulkanologi", "bahaya", "pemantauan"],
    geography: ["Global", "Indonesia"],
    relatedSourceIds: [],
    limitations: ["Sebagian besar artikel berbayar."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "iucn-red-list-page",
    title: "IUCN Red List of Threatened Species",
    publicationType: "dataset",
    publisherOrInstitution: "International Union for Conservation of Nature (IUCN)",
    sourceUrl: "https://www.iucnredlist.org",
    language: "en",
    accessType: "open_access",
    synopsis:
      "Basis data dan publikasi penilaian status konservasi spesies dunia. Tiap spesies punya lembar penilaian dengan status, sebaran, ancaman, dan tren populasi. Banyak satwa Indonesia, dari komodo sampai badak Jawa, dinilai di sini.",
    whyItMatters:
      "Otoritas global untuk status keterancaman spesies; rujukan utama saat membaca konservasi satwa Indonesia.",
    topics: ["konservasi", "status keterancaman", "biodiversitas"],
    geography: ["Global", "Indonesia"],
    relatedSourceIds: ["iucn-red-list-komodo", "iucn-red-list-badak-jawa"],
    limitations: ["Penilaian diperbarui berkala; rujuk lembar spesies untuk tahun dan metode."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "smithsonian-gvp",
    title: "Global Volcanism Program, Volcanoes of the World",
    publicationType: "institutional_page",
    publisherOrInstitution: "Smithsonian Institution",
    sourceUrl: "https://volcano.si.edu",
    language: "en",
    accessType: "open_access",
    synopsis:
      "Katalog gunung api dunia oleh Smithsonian, memuat riwayat letusan, tipe, dan data setiap gunung api, termasuk ratusan gunung api Indonesia. Menjadi rujukan standar untuk identitas dan sejarah gunung api.",
    whyItMatters:
      "Indonesia memiliki salah satu konsentrasi gunung api aktif terbanyak; katalog ini melacak riwayatnya secara konsisten.",
    topics: ["gunung api", "geologi", "katalog"],
    geography: ["Global", "Indonesia"],
    relatedSourceIds: ["gvp-krakatau", "gvp-merapi", "gvp-toba"],
    limitations: ["Data ringkas per gunung; rincian peristiwa perlu rujukan tambahan."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "nasa-earth-observatory",
    title: "NASA Earth Observatory",
    publicationType: "institutional_page",
    publisherOrInstitution: "NASA",
    sourceUrl: "https://earthobservatory.nasa.gov",
    language: "en",
    accessType: "open_access",
    synopsis:
      "Publikasi NASA yang menampilkan citra satelit dan artikel tentang peristiwa Bumi, dari letusan dan kebakaran sampai banjir. Banyak citra Indonesia, seperti kabut asap dan runtuhan Anak Krakatau, didokumentasikan di sini dengan gambar domain publik.",
    whyItMatters:
      "Sumber citra satelit domain publik yang berguna untuk melihat perubahan lanskap dan bencana di Indonesia.",
    topics: ["citra satelit", "bencana", "lingkungan"],
    geography: ["Global", "Indonesia"],
    relatedSourceIds: ["nasa-anak-krakatau-collapse"],
    limitations: ["Bersifat populer-ilmiah; bukan jurnal peer-review."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "unesco-world-heritage",
    title: "UNESCO World Heritage Centre",
    publicationType: "institutional_page",
    publisherOrInstitution: "UNESCO",
    sourceUrl: "https://whc.unesco.org/en/list/",
    language: "en",
    accessType: "open_access",
    synopsis:
      "Daftar dan dokumen resmi Situs Warisan Dunia, termasuk kawasan alam Indonesia seperti Ujung Kulon, Komodo, dan hutan hujan Sumatra. Tiap situs punya berkas penilaian dan status konservasinya.",
    whyItMatters:
      "Memberi pengakuan dan dokumentasi resmi untuk kawasan alam penting Indonesia.",
    topics: ["warisan dunia", "kawasan lindung", "konservasi"],
    geography: ["Global", "Indonesia"],
    relatedSourceIds: ["ujung-kulon-unesco", "komodo-unesco", "unesco-sumatra-rainforest"],
    limitations: ["Dokumen administratif; data ekologi rinci ada pada lampiran teknis."],
    checkedAt: CHECKED,
  }),
  p({
    slug: "biodiversity-heritage-library",
    title: "Biodiversity Heritage Library (BHL)",
    publicationType: "archive_record",
    publisherOrInstitution: "Biodiversity Heritage Library Consortium",
    sourceUrl: "https://www.biodiversitylibrary.org",
    language: "en",
    accessType: "open_access",
    synopsis:
      "Perpustakaan digital literatur keanekaragaman hayati, banyak berisi buku dan monograf lama yang sudah domain publik, termasuk catatan naturalis tentang Hindia Belanda. Sumber penting untuk arsip alam Nusantara.",
    whyItMatters:
      "Membuka akses ke literatur sejarah alam Indonesia yang dulu sulit dijangkau, dengan banyak visual domain publik.",
    topics: ["arsip alam", "sejarah alam", "literatur"],
    geography: ["Global", "Indonesia"],
    relatedSourceIds: ["ouwens-komodo-bhl-1912"],
    limitations: ["Banyak materi berbahasa Belanda atau Latin dan berformat lama."],
    checkedAt: CHECKED,
  }),
];
