import type { RawPublication } from "@/lib/types";
import { p } from "../_pub";

const CHECKED = "2026-06-13";
void CHECKED;

/**
 * Batch 1: specific, real open-access publications (papers) about Indonesian
 * nature, conservation, geology, and ecology. Each record is one SPECIFIC paper
 * with a real title, authors, DOI, and a VERIFIED official open-access PDF URL
 * (checked to resolve to a real PDF). Sourced via OpenAlex; PDFs from the
 * publisher / repository / institution. No invented data, no mirrors, no Sci-Hub.
 */
export const publicationsBatch1: RawPublication[] = [
  p({
    slug: "anak-krakatau",
    title: "Modelling of the tsunami from the December 22, 2018 lateral collapse of Anak Krakatau volcano in the Sunda Straits, Indonesia",
    publicationType: "journal_article",
    publisherOrInstitution: "Springer Nature",
    journalOrCollection: "Scientific Reports",
    authors: ["Stéphan T. Grilli", "David R. Tappin", "Steven Carey", "Sebastian Watt", "S. N. Ward", "Annette R. Grilli"],
    year: "2019",
    sourceUrl: "https://doi.org/10.1038/s41598-019-48327-6",
    doi: "10.1038/s41598-019-48327-6",
    pdfUrl: "https://www.nature.com/articles/s41598-019-48327-6.pdf",
    synopsis: "Studi pemodelan tsunami Selat Sunda 22 Desember 2018 sebagai akibat runtuhnya sisi tubuh Anak Krakatau. Penulis merekonstruksi bagaimana longsoran tubuh gunung api mendorong air dan menimbulkan gelombang tanpa gempa tektonik besar.",
    whyItMatters: "Rujukan ilmiah utama untuk memahami tsunami vulkanik di Indonesia dan keterbatasan sistem peringatan yang bertumpu pada gempa.",
    topics: ["tsunami", "gunung api", "Anak Krakatau", "Selat Sunda"],
    geography: ["Selat Sunda", "Indonesia"],
    language: "en",
    accessType: "open_access",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "kelud-eruption",
    title: "Lahar at Kali Konto after the 2014 Eruption of Kelud Volcano, East Java: Impacts and Risk",
    publicationType: "journal_article",
    publisherOrInstitution: "Universitas Muhammadiyah Surakarta",
    journalOrCollection: "Forum Geografi",
    authors: ["Suprapto Dibyosaputro", "Gilang Arya Dipayana", "Henky Nugraha", "Kartika Pratiwi", "Hogy Prima Valeda"],
    year: "2015",
    sourceUrl: "https://doi.org/10.23917/forgeo.v29i1.793",
    doi: "10.23917/forgeo.v29i1.793",
    pdfUrl: "http://journals.ums.ac.id/index.php/fg/article/download/793/521",
    synopsis: "Kajian lahar di Kali Konto setelah letusan Gunung Kelud 2014: dampak dan risikonya bagi kawasan di hilir. Membahas bagaimana material letusan bergerak sebagai aliran lahar dan ancamannya pada permukiman.",
    whyItMatters: "Menjelaskan bahaya lahar pasca-letusan, salah satu risiko utama gunung api berdanau kawah seperti Kelud.",
    topics: ["Kelud", "lahar", "gunung api", "bahaya"],
    geography: ["Kelud", "Jawa Timur", "Indonesia"],
    language: "en",
    accessType: "open_access",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "komodo-conservation",
    title: "Morphometric and Nutritional Assessment of Komodo Dragons (Varanus komodoensis, Ouwens 1912) on Komodo Island: Implications for Size Variation and Conservation",
    publicationType: "journal_article",
    publisherOrInstitution: "Jomard Publishing",
    journalOrCollection: "Advances in Biology & Earth Sciences",
    authors: [],
    year: "2025",
    sourceUrl: "https://doi.org/10.62476/abes.103460",
    doi: "10.62476/abes.103460",
    pdfUrl: "https://api.jomardpublishing.com/api/main/articles/download?source=storage/journals/advances-in-biology-earth-sciences/issues/pdf/2025/morphometric-and-nutritional-assessment-of-komodo-dragons-varanus-komodoensis-ouwens-1912-on-komodo-island-implications-for-size-variation-and-conservation.pdf",
    synopsis: "Penilaian morfometri dan nutrisi komodo (Varanus komodoensis) di Pulau Komodo, dan implikasinya pada variasi ukuran tubuh serta konservasi. Mengukur ciri fisik populasi untuk memahami kondisi dan kebutuhan pengelolaannya.",
    whyItMatters: "Menambah data lapangan terbaru tentang kondisi fisik populasi komodo untuk mendukung pengelolaan konservasi.",
    topics: ["Komodo", "morfometri", "konservasi", "reptil"],
    geography: ["Komodo", "Nusa Tenggara Timur", "Indonesia"],
    language: "en",
    accessType: "official_pdf_available",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "tarsier-sulawesi",
    title: "Responding to forest degradation: altered habitat use by Dian's tarsier <i>Tarsius dianae</i> in Sulawesi, Indonesia",
    publicationType: "journal_article",
    publisherOrInstitution: "Cambridge University Press (Fauna & Flora International)",
    journalOrCollection: "Oryx",
    authors: ["Stefan Merker", "Indra Yustian", "Michael Mühlenberg"],
    year: "2005",
    sourceUrl: "https://doi.org/10.1017/s0030605305000438",
    doi: "10.1017/s0030605305000438",
    pdfUrl: "https://www.cambridge.org/core/services/aop-cambridge-core/content/view/2ADECB487B2A16F2337DDE2232E77F1A/S0030605305000438a.pdf/div-class-title-responding-to-forest-degradation-altered-habitat-use-by-dian-s-tarsier-span-class-italic-tarsius-dianae-span-in-sulawesi-indonesia-div.pdf",
    synopsis: "Studi tentang perubahan penggunaan habitat oleh tarsius (Tarsius dianae) sebagai respons terhadap degradasi hutan di Sulawesi. Menelusuri bagaimana primata nokturnal ini menyesuaikan diri ketika hutannya terganggu.",
    whyItMatters: "Memperlihatkan dampak degradasi hutan pada primata endemik Sulawesi, relevan bagi konservasi Wallacea.",
    topics: ["tarsius", "primata", "degradasi hutan", "Sulawesi"],
    geography: ["Sulawesi", "Indonesia"],
    language: "en",
    accessType: "official_pdf_available",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "coelacanth-indonesia",
    title: "First insight into accumulation of characteristics and tissues distribution of PCBs, PBDEs, and other BFRs in the living Indonesian coelacanth (Latimeria menadoensis)",
    publicationType: "journal_article",
    publisherOrInstitution: "Research Square (pracetak)",
    journalOrCollection: "Research Square",
    authors: ["Dede Falahudin", "Frensly Demianus Hukom", "Zainal Arifin", "Dirhamsyah Dirhamsyah", "Teguh Peristiwady", "Agus Sudaryanto"],
    year: "2022",
    sourceUrl: "https://doi.org/10.21203/rs.3.rs-2091749/v1",
    doi: "10.21203/rs.3.rs-2091749/v1",
    pdfUrl: "https://www.researchsquare.com/article/rs-2091749/latest.pdf",
    synopsis: "Tinjauan awal akumulasi dan sebaran senyawa pencemar (PCB, PBDE, dan penghambat api brominasi lain) pada coelacanth hidup Indonesia (Latimeria menadoensis). Pracetak yang menyoroti jejak pencemaran pada ikan purba laut dalam.",
    whyItMatters: "Mengaitkan fosil hidup laut dalam Indonesia dengan isu pencemaran modern; perlu diingat statusnya masih pracetak.",
    topics: ["coelacanth", "ikan", "pencemaran", "laut dalam"],
    geography: ["Sulawesi", "Indonesia"],
    language: "en",
    accessType: "official_pdf_available",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka.", "Naskah ini berstatus pracetak (preprint), belum tentu melewati tinjauan sejawat penuh."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "javan-rhino",
    title: "Estimating the population structure of Javan rhinos (Rhinoceros sondaicus) in Ujung Kulon National Park using the mark- recapture method based on video and camera trap identification",
    publicationType: "journal_article",
    publisherOrInstitution: "IUCN SSC African Elephant, African Rhino & Asian Rhino Specialist Groups",
    journalOrCollection: "Pachyderm",
    authors: ["Adhi Hariyadi", "Agus Priambudi", "Ridwan Setiawan", "Daryan Daryan", "Asep Yayus", "Hendra Purnama"],
    year: "2011",
    sourceUrl: "https://doi.org/10.69649/pachyderm.v49i.254",
    doi: "10.69649/pachyderm.v49i.254",
    pdfUrl: "https://pachydermjournal.org/index.php/pachyderm/article/download/254/215",
    synopsis: "Estimasi struktur populasi badak Jawa (Rhinoceros sondaicus) di Taman Nasional Ujung Kulon dengan metode mark-recapture berbasis identifikasi video dan kamera jebak. Memetakan jumlah dan komposisi populasi yang tersisa.",
    whyItMatters: "Data populasi langsung untuk mamalia besar paling langka di Indonesia, inti dari upaya penyelamatannya.",
    topics: ["badak Jawa", "Ujung Kulon", "populasi", "konservasi"],
    geography: ["Ujung Kulon", "Banten", "Indonesia"],
    language: "en",
    accessType: "open_access",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "mangrove-blue-carbon",
    title: "Environmental conditions to support blue carbon storage in mangrove forest: A case study in the mangrove forest, Nusa Lembongan, Bali, Indonesia",
    publicationType: "journal_article",
    publisherOrInstitution: "Universitas Sebelas Maret (Smujo)",
    journalOrCollection: "Biodiversitas Journal of Biological Diversity",
    authors: ["Cindy Clara Pricillia", "Herdis Herdiansyah", "Mufti Petala Patria"],
    year: "2021",
    sourceUrl: "https://doi.org/10.13057/biodiv/d220636",
    doi: "10.13057/biodiv/d220636",
    pdfUrl: "https://smujo.id/biodiv/article/download/8322/4886",
    synopsis: "Studi kasus kondisi lingkungan yang mendukung simpanan karbon biru di hutan mangrove Nusa Lembongan, Bali. Mengukur faktor yang menentukan seberapa besar mangrove menyimpan karbon.",
    whyItMatters: "Bukti lapangan dari Indonesia tentang nilai karbon biru mangrove untuk iklim dan pesisir.",
    topics: ["mangrove", "karbon biru", "pesisir", "Bali"],
    geography: ["Nusa Lembongan", "Bali", "Indonesia"],
    language: "en",
    accessType: "open_access",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "jakarta-subsidence",
    title: "Analysis Of Land Subsidence Relationship With Groundwater Table Depletion In South Jakarta",
    publicationType: "journal_article",
    publisherOrInstitution: "Al-Makki Publisher",
    journalOrCollection: "Jurnal Ekonomi Teknologi dan Bisnis (JETBIS)",
    authors: ["Andreas Julio Nembo", "Afiat Anugrahadi", "Himmes Fitra Yuda"],
    year: "2023",
    sourceUrl: "https://doi.org/10.57185/jetbis.v2i2.33",
    doi: "10.57185/jetbis.v2i2.33",
    pdfUrl: "https://jetbis.al-makkipublisher.com/index.php/al/article/download/33/79",
    synopsis: "Analisis hubungan antara penurunan muka tanah dan penurunan muka air tanah di Jakarta Selatan. Menelusuri bagaimana pengambilan air tanah berkaitan dengan amblasnya permukaan.",
    whyItMatters: "Mendukung pemahaman bahwa banjir Jakarta diperparah penurunan tanah, bukan hanya kenaikan laut.",
    topics: ["penurunan tanah", "air tanah", "Jakarta"],
    geography: ["Jakarta", "Indonesia"],
    language: "en",
    accessType: "open_access",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "proboscis-monkey",
    title: "Population dynamics of the proboscis monkey<i>Nasalis larvatus</i>in the Lower Kinabatangan, Sabah, Borneo, Malaysia",
    publicationType: "journal_article",
    publisherOrInstitution: "Cambridge University Press (Fauna & Flora International)",
    journalOrCollection: "Oryx",
    authors: ["Ikki Matsuda", "Nicola K. Abram", "Danica J. Stark", "John Chih Mun Sha", "Marc Ancrenaz", "Benoît Goossens"],
    year: "2018",
    sourceUrl: "https://doi.org/10.1017/s0030605318000467",
    doi: "10.1017/s0030605318000467",
    pdfUrl: "https://www.cambridge.org/core/services/aop-cambridge-core/content/view/1026A363A3E9117F94C43C312BCAD781/S0030605318000467a.pdf/div-class-title-population-dynamics-of-the-proboscis-monkey-span-class-italic-nasalis-larvatus-span-in-the-lower-kinabatangan-sabah-borneo-malaysia-div.pdf",
    synopsis: "Kajian dinamika populasi bekantan (Nasalis larvatus) di kawasan Kinabatangan Bawah, Sabah, Borneo. Memantau perubahan jumlah dan sebaran monyet berhidung besar ini di habitat sungai dan mangrove.",
    whyItMatters: "Data populasi bekantan di Borneo yang relevan bagi konservasi monyet endemik dan habitat riparian.",
    topics: ["bekantan", "primata", "populasi", "Borneo"],
    geography: ["Kinabatangan", "Borneo"],
    language: "en",
    accessType: "official_pdf_available",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "javan-gibbon",
    title: "Conservation Of The Javan Gibbon Hylobates Moloch: Population Estimates, Local Extinctions, And Conservation Priorities",
    publicationType: "journal_article",
    publisherOrInstitution: "University of Amsterdam",
    journalOrCollection: "UvA-DARE (University of Amsterdam)",
    authors: ["Vincent Nijman"],
    year: "2004",
    sourceUrl: "https://doi.org/10.5281/zenodo.13244460",
    doi: "10.5281/zenodo.13244460",
    pdfUrl: "https://pure.uva.nl/ws/files/3583562/35159_Nijman_Hmol_RafflesBull.pdf",
    synopsis: "Estimasi populasi, kepunahan lokal, dan prioritas konservasi owa Jawa (Hylobates moloch). Memetakan di mana owa masih bertahan dan di mana sudah hilang di sisa hutan Jawa.",
    whyItMatters: "Dasar penting untuk memprioritaskan perlindungan owa Jawa di pulau yang hutannya sangat menyusut.",
    topics: ["owa Jawa", "primata", "populasi", "konservasi"],
    geography: ["Jawa", "Indonesia"],
    language: "en",
    accessType: "official_pdf_available",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "sulawesi-macaque",
    title: "A Comparison of the Activity Budgets of Wild and Captive Sulawesi Crested Black Macaques<i>(Macaca Nigra)</i>",
    publicationType: "journal_article",
    publisherOrInstitution: "Cambridge University Press (UFAW)",
    journalOrCollection: "Animal Welfare",
    authors: ["Vicky Melfi", "A. T. C. Feistner"],
    year: "2002",
    sourceUrl: "https://doi.org/10.1017/s0962728600028165",
    doi: "10.1017/s0962728600028165",
    pdfUrl: "https://www.cambridge.org/core/services/aop-cambridge-core/content/view/593624FE1172DCC3588FDFEE38EE3867/S0962728600028165a.pdf/div-class-title-a-comparison-of-the-activity-budgets-of-wild-and-captive-sulawesi-crested-black-macaques-span-class-italic-macaca-nigra-span-div.pdf",
    synopsis: "Perbandingan anggaran aktivitas yaki (Macaca nigra) liar dan yang ditangkarkan. Membandingkan bagaimana monyet hitam Sulawesi membagi waktunya di alam versus penangkaran.",
    whyItMatters: "Memberi konteks perilaku yaki, primata endemik Sulawesi yang terancam kritis.",
    topics: ["yaki", "primata", "perilaku", "Sulawesi"],
    geography: ["Sulawesi", "Indonesia"],
    language: "en",
    accessType: "official_pdf_available",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "seagrass-indonesia",
    title: "Impacts of dredging and restoration on sedimentary carbon stocks in seagrass meadows of Pari Island, Indonesia",
    publicationType: "journal_article",
    publisherOrInstitution: "Springer Nature",
    journalOrCollection: "Scientific Reports",
    authors: ["Yusmiana P. Rahayu", "Gary A. Kendrick", "Pere Masqué", "Wawan Kiswara", "Hadiwijaya Lesmana Salim", "Ali Arman Lubis"],
    year: "2025",
    sourceUrl: "https://doi.org/10.1038/s41598-025-03870-3",
    doi: "10.1038/s41598-025-03870-3",
    pdfUrl: "https://www.nature.com/articles/s41598-025-03870-3.pdf",
    synopsis: "Studi dampak pengerukan dan restorasi terhadap simpanan karbon sedimen di padang lamun Pulau Pari, Indonesia. Mengukur bagaimana gangguan dan pemulihan memengaruhi karbon yang tersimpan di dasar laut.",
    whyItMatters: "Menunjukkan nilai karbon padang lamun Indonesia dan kerentanannya terhadap pengerukan.",
    topics: ["lamun", "karbon", "pengerukan", "restorasi"],
    geography: ["Pulau Pari", "Indonesia"],
    language: "en",
    accessType: "open_access",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "reef-fish-indonesia",
    title: "Diversity of reef fish in Halang Melingkau Island, South Kalimantan, Indonesia",
    publicationType: "journal_article",
    publisherOrInstitution: "Universitas Sebelas Maret (Smujo)",
    journalOrCollection: "Biodiversitas Journal of Biological Diversity",
    authors: ["Frans Tony", "Soemarno Soemarno", "Dewa Gede Raka Wiadnya", "Luchman Hakim"],
    year: "2020",
    sourceUrl: "https://doi.org/10.13057/biodiv/d211046",
    doi: "10.13057/biodiv/d211046",
    pdfUrl: "https://smujo.id/biodiv/article/download/5947/4299",
    synopsis: "Inventarisasi keanekaragaman ikan karang di Pulau Halang Melingkau, Kalimantan Selatan. Mencatat jenis-jenis ikan yang menghuni terumbu di perairan tersebut.",
    whyItMatters: "Data dasar keanekaragaman ikan karang Indonesia untuk pemantauan kesehatan terumbu.",
    topics: ["ikan karang", "keanekaragaman", "laut", "Kalimantan"],
    geography: ["Kalimantan Selatan", "Indonesia"],
    language: "en",
    accessType: "open_access",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "new-species-zookeys",
    title: "Description of a new Moridilla species from North Sulawesi, Indonesia (Mollusca: Nudibranchia: Aeolidioidea) - based on MicroCT, histological and molecular analyses",
    publicationType: "journal_article",
    publisherOrInstitution: "Magnolia Press",
    journalOrCollection: "Zootaxa",
    authors: ["Dorothee Schillo", "Benjamin Wipfler‍", "Nani Undap", "Adelfia Papu", "Nils Böhringer", "Jan-Hendrik Eisenbarth"],
    year: "2019",
    sourceUrl: "https://doi.org/10.11646/zootaxa.4652.2.3",
    doi: "10.11646/zootaxa.4652.2.3",
    pdfUrl: "https://www.biotaxa.org/Zootaxa/article/download/zootaxa.4652.2.3/50131",
    synopsis: "Deskripsi spesies siput laut (nudibranch) baru, Moridilla, dari Sulawesi Utara, berdasarkan MicroCT, histologi, dan analisis molekuler. Contoh penemuan dan penamaan kekayaan hayati laut Indonesia.",
    whyItMatters: "Bukti bahwa laut Indonesia masih menyimpan spesies yang belum dideskripsikan, penting bagi taksonomi.",
    topics: ["spesies baru", "moluska", "taksonomi", "Sulawesi"],
    geography: ["Sulawesi Utara", "Indonesia"],
    language: "en",
    accessType: "official_pdf_available",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "sea-level-coast-id",
    title: "IMPACT OF SEA LEVEL RISE TO COASTAL ECOLOGY: A CASE STUDY ON THE NORTHERN PART OF JAVA ISLAND, INDONESIA",
    publicationType: "journal_article",
    publisherOrInstitution: "Adam Mickiewicz University (Sciendo)",
    journalOrCollection: "Quaestiones Geographicae",
    authors: ["Muh Aris Marfai"],
    year: "2014",
    sourceUrl: "https://doi.org/10.2478/quageo-2014-0008",
    doi: "10.2478/quageo-2014-0008",
    pdfUrl: "https://sciendo.com/pdf/10.2478/quageo-2014-0008",
    synopsis: "Studi kasus dampak kenaikan muka laut terhadap ekologi pesisir di bagian utara Pulau Jawa. Menelaah bagaimana naiknya laut mengubah lingkungan pantai dan kehidupan di sekitarnya.",
    whyItMatters: "Relevan untuk pesisir utara Jawa yang padat dan rentan terhadap kenaikan laut serta rob.",
    topics: ["kenaikan laut", "pesisir", "ekologi", "Jawa"],
    geography: ["Jawa Utara", "Indonesia"],
    language: "en",
    accessType: "open_access",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "rafflesia",
    title: "Ex situ conservation of Rafflesia patma (Rafflesiaceae) in Bogor Botanical Gardens (Indonesia)",
    publicationType: "journal_article",
    publisherOrInstitution: "Nature Conservation Research",
    journalOrCollection: "Nature Conservation Research",
    authors: ["Sofi Mursidawati"],
    year: "2017",
    sourceUrl: "https://doi.org/10.24189/ncr.2017.014",
    doi: "10.24189/ncr.2017.014",
    pdfUrl: "http://ncr-journal.bear-land.org/uploads/c44f608c4a758c4ffcefdce383f7c875.pdf",
    synopsis: "Laporan konservasi ex situ Rafflesia patma di Kebun Raya Bogor. Mendokumentasikan upaya menumbuhkan bunga parasit raksasa ini di luar habitat aslinya.",
    whyItMatters: "Menyoroti tantangan melestarikan tumbuhan ikonik dan sulit dibudidayakan khas Indonesia.",
    topics: ["Rafflesia", "tumbuhan", "konservasi ex situ"],
    geography: ["Bogor", "Jawa Barat", "Indonesia"],
    language: "en",
    accessType: "open_access",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "orchid-id",
    title: "Diversity of orchids (Orchidaceae) and host trees at Padang, West Sumatra, Indonesia: A preliminary step towards germplasm conservation",
    publicationType: "journal_article",
    publisherOrInstitution: "IPB University",
    journalOrCollection: "Jurnal Agronomi Indonesia (Indonesian Journal of Agronomy)",
    authors: ["Ryan Budi Setiawan", "Mellyyana Handayani", "Alifma Rahimmi Nanda", "Dian Sukma", "Alfazlul Rahmi", "Agil Syahputra"],
    year: "2024",
    sourceUrl: "https://doi.org/10.24831/jai.v52i2.56159",
    doi: "10.24831/jai.v52i2.56159",
    pdfUrl: "https://journal.ipb.ac.id/jurnalagronomi/article/download/56159/29336",
    synopsis: "Kajian keanekaragaman anggrek (Orchidaceae) dan pohon inangnya di Padang, Sumatra Barat, sebagai langkah awal konservasi plasma nutfah. Mencatat jenis anggrek dan pohon tempat mereka menempel.",
    whyItMatters: "Data dasar untuk konservasi anggrek Indonesia yang kaya jenis tetapi rentan.",
    topics: ["anggrek", "keanekaragaman", "tumbuhan", "Sumatra"],
    geography: ["Padang", "Sumatra Barat", "Indonesia"],
    language: "en",
    accessType: "open_access",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "butterfly-id",
    title: "Diversity of butterflies (Lepidoptera) across rainforest transformation systems in Jambi, Sumatra, Indonesia",
    publicationType: "journal_article",
    publisherOrInstitution: "Universitas Sebelas Maret (Smujo)",
    journalOrCollection: "Biodiversitas Journal of Biological Diversity",
    authors: ["Rawati Panjaitan", "Jochen Drescher", "Damayanti Buchori", "Djunijanti Peggie", "Idham Sakti Harahap", "Stefan Scheu"],
    year: "2020",
    sourceUrl: "https://doi.org/10.13057/biodiv/d211117",
    doi: "10.13057/biodiv/d211117",
    pdfUrl: "https://smujo.id/biodiv/article/download/6152/4344",
    synopsis: "Studi keanekaragaman kupu-kupu di berbagai sistem transformasi hutan hujan di Jambi, Sumatra. Membandingkan kelimpahan kupu-kupu antara hutan dan lahan yang sudah diubah.",
    whyItMatters: "Menunjukkan bagaimana perubahan hutan menjadi perkebunan memengaruhi serangga penyerbuk.",
    topics: ["kupu-kupu", "keanekaragaman", "transformasi hutan", "Sumatra"],
    geography: ["Jambi", "Sumatra", "Indonesia"],
    language: "en",
    accessType: "open_access",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "bird-diversity-id",
    title: "Preliminary study on bird and mammal diversity at ecosystem restored areas in the Gunung Gede Pangrango National Park, West Java, Indonesia",
    publicationType: "journal_article",
    publisherOrInstitution: "Universitas Pakuan",
    journalOrCollection: "Indonesian Journal of Applied Environmental Studies",
    authors: ["Anton Ario", "Iip Latipah Syaepulloh", "Dede Rahmatulloh", "Irvan Maulana", "Supian Supian", "Dedi Junaedi"],
    year: "2020",
    sourceUrl: "https://doi.org/10.33751/injast.v1i2.2190",
    doi: "10.33751/injast.v1i2.2190",
    pdfUrl: "https://journal.unpak.ac.id/index.php/InJAST/article/download/2190/pdf",
    synopsis: "Studi awal keanekaragaman burung dan mamalia di area restorasi ekosistem Taman Nasional Gunung Gede Pangrango, Jawa Barat. Memantau pulihnya satwa di kawasan yang sedang direstorasi.",
    whyItMatters: "Bukti bahwa restorasi ekosistem dapat mengembalikan keanekaragaman satwa di Jawa.",
    topics: ["burung", "mamalia", "restorasi", "taman nasional"],
    geography: ["Gunung Gede Pangrango", "Jawa Barat", "Indonesia"],
    language: "en",
    accessType: "official_pdf_available",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "marine-protected-id",
    title: "Participation in devolved commons management: Multiscale socioeconomic factors related to individuals’ participation in community-based management of marine protected areas in Indonesia",
    publicationType: "journal_article",
    publisherOrInstitution: "Elsevier",
    journalOrCollection: "Environmental Science & Policy",
    authors: ["Georgina G. Gurney", "Joshua E. Cinner", "J. Sartin", "Robert L. Pressey", "Natalie C. Ban", "Nadine Marshall"],
    year: "2016",
    sourceUrl: "https://doi.org/10.1016/j.envsci.2016.04.015",
    doi: "10.1016/j.envsci.2016.04.015",
    pdfUrl: "https://researchonline.jcu.edu.au/45579/6/Gurney2016.pdf",
    synopsis: "Analisis faktor sosial-ekonomi yang memengaruhi partisipasi individu dalam pengelolaan kawasan konservasi laut berbasis masyarakat di Indonesia. Menelusuri apa yang membuat orang ikut atau tidak ikut mengelola laut bersama.",
    whyItMatters: "Penting untuk memahami mengapa pengelolaan laut berbasis masyarakat berhasil atau gagal.",
    topics: ["kawasan konservasi laut", "masyarakat", "tata kelola"],
    geography: ["Indonesia"],
    language: "en",
    accessType: "official_pdf_available",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "fisheries-id",
    title: "Incorporating the Ecological, Socio-economic and Institutional Conceptual Model Framework for Sustainable Management of Small-scale Mud Crab (Scylla serrata) Fishery in Western Seram Regency, Indonesia",
    publicationType: "journal_article",
    publisherOrInstitution: "Mahidol University",
    journalOrCollection: "Environment and Natural Resources Journal",
    authors: ["Yuliana Natan", "Johannes M.S. Tetelepta", "J A Pattikawa", "O T S Ongkers"],
    year: "2021",
    sourceUrl: "https://doi.org/10.32526/ennrj/19/2020189",
    doi: "10.32526/ennrj/19/2020189",
    pdfUrl: "https://ph02.tci-thaijo.org/index.php/ennrj/article/download/241634/165196",
    synopsis: "Kerangka konseptual ekologi, sosial-ekonomi, dan kelembagaan untuk pengelolaan berkelanjutan perikanan kepiting bakau (Scylla serrata) di Seram Barat. Memadukan tiga dimensi untuk mengelola perikanan skala kecil.",
    whyItMatters: "Model pengelolaan perikanan pesisir berkelanjutan yang relevan bagi banyak wilayah Indonesia.",
    topics: ["perikanan", "kepiting bakau", "pengelolaan", "Maluku"],
    geography: ["Seram", "Maluku", "Indonesia"],
    language: "en",
    accessType: "open_access",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "river-water-java",
    title: "Water Quality Assessment of Cimanuk River in West Java Using Pollution Index",
    publicationType: "journal_article",
    publisherOrInstitution: "EDP Sciences",
    journalOrCollection: "E3S Web of Conferences",
    authors: ["Ihya Sulthonuddin", "Djoko M. Hartono", "Suyud Warno Utomo"],
    year: "2018",
    sourceUrl: "https://doi.org/10.1051/e3sconf/20186804009",
    doi: "10.1051/e3sconf/20186804009",
    pdfUrl: "https://www.e3s-conferences.org/articles/e3sconf/pdf/2018/43/e3sconf_sricoenv2018_04009.pdf",
    synopsis: "Penilaian kualitas air Sungai Cimanuk di Jawa Barat menggunakan indeks pencemaran. Mengukur tingkat pencemaran sungai berdasarkan parameter air.",
    whyItMatters: "Menambah data kualitas air sungai Jawa yang menopang pertanian dan permukiman.",
    topics: ["kualitas air", "sungai", "pencemaran", "Jawa Barat"],
    geography: ["Sungai Cimanuk", "Jawa Barat", "Indonesia"],
    language: "en",
    accessType: "open_access",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "agroforestry-id",
    title: "Ecosystem services provided by agroforestry home gardens in Bengkulu, Indonesia: Smallholder utilization, biodiversity conservation, and carbon storage",
    publicationType: "journal_article",
    publisherOrInstitution: "Universitas Sebelas Maret (Smujo)",
    journalOrCollection: "Biodiversitas Journal of Biological Diversity",
    authors: ["Wiryono Wiryono", "Paul Kristiansen", "Lisa Lobry de Bruyn", "Saprinurdin Saprinurdin", "Steffanie Nurliana"],
    year: "2023",
    sourceUrl: "https://doi.org/10.13057/biodiv/d240518",
    doi: "10.13057/biodiv/d240518",
    pdfUrl: "https://smujo.id/biodiv/article/download/14464/6800",
    synopsis: "Kajian jasa ekosistem pekarangan agroforestri di Bengkulu: pemanfaatan oleh petani kecil, konservasi keanekaragaman hayati, dan penyimpanan karbon. Menunjukkan bagaimana kebun campuran menopang banyak fungsi sekaligus.",
    whyItMatters: "Bukti bahwa sistem pertanian tradisional Indonesia dapat menyatukan pangan, keanekaragaman, dan karbon.",
    topics: ["agroforestri", "jasa ekosistem", "karbon", "Bengkulu"],
    geography: ["Bengkulu", "Sumatra", "Indonesia"],
    language: "en",
    accessType: "open_access",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  }),
  p({
    slug: "bamboo-id",
    title: "Bamboo diversity in Weh Island, Aceh, Indonesia",
    publicationType: "journal_article",
    publisherOrInstitution: "Universitas Sebelas Maret (Smujo)",
    journalOrCollection: "Biodiversitas Journal of Biological Diversity",
    authors: ["Muhammad Azli Ritonga", "Syamsuardi Syamsuardi", "Nurainas Nurainas", "I Putu Gede P. Damayanto"],
    year: "2023",
    sourceUrl: "https://doi.org/10.13057/biodiv/d240508",
    doi: "10.13057/biodiv/d240508",
    pdfUrl: "https://smujo.id/biodiv/article/download/14260/6794",
    synopsis: "Inventarisasi keanekaragaman bambu di Pulau Weh, Aceh. Mencatat jenis-jenis bambu yang tumbuh di pulau paling barat Indonesia.",
    whyItMatters: "Data dasar keanekaragaman bambu, tumbuhan serbaguna yang penting secara ekologi dan budaya.",
    topics: ["bambu", "keanekaragaman", "tumbuhan", "Aceh"],
    geography: ["Pulau Weh", "Aceh", "Indonesia"],
    language: "en",
    accessType: "open_access",
    relatedSourceIds: [],
    limitations: ["Sinopsis adalah ringkasan NaLI; baca naskah lengkap di PDF/sumber asli untuk detail dan angka."],
    checkedAt: "2026-06-13",
  })
];
