// AUTO-GENERATED by `node scripts/lab/ghost/build-signals.mjs --emit-sample`.
// Do not edit by hand. Snapshot of real iNaturalist needs-ID ghost signals
// (+ labeled CONTOH samples for the key-gated Xeno-canto/YouTube sources).
// Used as the /lab/signals fallback when ghost_signals is empty. Internal,
// unverified anomalies, never public.
import type { GhostSignalRow } from "@/lib/lab/ghost";

export const SAMPLE_GHOST_SIGNALS: GhostSignalRow[] = [
  {
    "source": "inaturalist",
    "external_id": "376472297",
    "title": "Katydids, Crickets, and Allies",
    "url": "https://www.inaturalist.org/observations/376472297",
    "observed_on": "2025-01-01",
    "location_label": "2PRJ+W85, Batu Ampar, Kec. Kemuning, Kabupaten Indragiri Hilir, Riau 29274, Indonesia",
    "taxon_hint": "Ensifera",
    "summary": "Observasi iNaturalist berstatus needs-ID, baru teridentifikasi sampai tingkat suborder (Ensifera).",
    "score": 86,
    "signals": [
      {
        "key": "mystery",
        "label": "Kedalaman misteri (belum teridentifikasi)",
        "value": 0.8,
        "weight": 0.45,
        "points": 36,
        "note": "Teridentifikasi sampai tingkat suborder"
      },
      {
        "key": "recency",
        "label": "Kebaruan",
        "value": 0.85,
        "weight": 0.35,
        "points": 30,
        "note": "Tertanggal 2025-01-01"
      },
      {
        "key": "locatable",
        "label": "Dapat dilacak (ada lokasi)",
        "value": 1,
        "weight": 0.2,
        "points": 20,
        "note": "2PRJ+W85, Batu Ampar, Kec. Kemuning, Kabupaten Indragiri Hilir, Riau 29274, Indonesia"
      }
    ],
    "provenance": "api",
    "updated_at": "2026-06-29T07:53:34.659Z",
    "status": "signal",
    "created_at": "2026-06-29T07:53:34.659Z"
  },
  {
    "source": "inaturalist",
    "external_id": "376469027",
    "title": "Softshell Turtles",
    "url": "https://www.inaturalist.org/observations/376469027",
    "observed_on": "2026-06-28",
    "location_label": "Pasar Bawah, Kp. Dalam, Senapelan, Kota Pekanbaru, Riau, Indonesia",
    "taxon_hint": "Trionychinae",
    "summary": "Observasi iNaturalist berstatus needs-ID, baru teridentifikasi sampai tingkat subfamily (Trionychinae).",
    "score": 82,
    "signals": [
      {
        "key": "mystery",
        "label": "Kedalaman misteri (belum teridentifikasi)",
        "value": 0.6,
        "weight": 0.45,
        "points": 27,
        "note": "Teridentifikasi sampai tingkat subfamily"
      },
      {
        "key": "recency",
        "label": "Kebaruan",
        "value": 1,
        "weight": 0.35,
        "points": 35,
        "note": "Tertanggal 2026-06-28"
      },
      {
        "key": "locatable",
        "label": "Dapat dilacak (ada lokasi)",
        "value": 1,
        "weight": 0.2,
        "points": 20,
        "note": "Pasar Bawah, Kp. Dalam, Senapelan, Kota Pekanbaru, Riau, Indonesia"
      }
    ],
    "provenance": "api",
    "updated_at": "2026-06-29T07:53:34.659Z",
    "status": "signal",
    "created_at": "2026-06-29T07:53:34.659Z"
  },
  {
    "source": "inaturalist",
    "external_id": "376467148",
    "title": "Water Striders",
    "url": "https://www.inaturalist.org/observations/376467148",
    "observed_on": "2026-06-29",
    "location_label": "5M6C+5CG, Duren, Beji, Kec. Ngawen, Kabupaten Gunungkidul, Daerah Istimewa Yogyakarta 55853, Indonesia",
    "taxon_hint": "Gerridae",
    "summary": "Observasi iNaturalist berstatus needs-ID, baru teridentifikasi sampai tingkat family (Gerridae).",
    "score": 82,
    "signals": [
      {
        "key": "mystery",
        "label": "Kedalaman misteri (belum teridentifikasi)",
        "value": 0.6,
        "weight": 0.45,
        "points": 27,
        "note": "Teridentifikasi sampai tingkat family"
      },
      {
        "key": "recency",
        "label": "Kebaruan",
        "value": 1,
        "weight": 0.35,
        "points": 35,
        "note": "Tertanggal 2026-06-29"
      },
      {
        "key": "locatable",
        "label": "Dapat dilacak (ada lokasi)",
        "value": 1,
        "weight": 0.2,
        "points": 20,
        "note": "5M6C+5CG, Duren, Beji, Kec. Ngawen, Kabupaten Gunungkidul, Daerah Istimewa Yogyakarta 55853, Indonesia"
      }
    ],
    "provenance": "api",
    "updated_at": "2026-06-29T07:53:34.659Z",
    "status": "signal",
    "created_at": "2026-06-29T07:53:34.659Z"
  },
  {
    "source": "inaturalist",
    "external_id": "376462300",
    "title": "Parrotfishes",
    "url": "https://www.inaturalist.org/observations/376462300",
    "observed_on": "2026-05-10",
    "location_label": "West Papua, ID",
    "taxon_hint": "Scarinae",
    "summary": "Observasi iNaturalist berstatus needs-ID, baru teridentifikasi sampai tingkat subfamily (Scarinae).",
    "score": 82,
    "signals": [
      {
        "key": "mystery",
        "label": "Kedalaman misteri (belum teridentifikasi)",
        "value": 0.6,
        "weight": 0.45,
        "points": 27,
        "note": "Teridentifikasi sampai tingkat subfamily"
      },
      {
        "key": "recency",
        "label": "Kebaruan",
        "value": 0.99,
        "weight": 0.35,
        "points": 35,
        "note": "Tertanggal 2026-05-10"
      },
      {
        "key": "locatable",
        "label": "Dapat dilacak (ada lokasi)",
        "value": 1,
        "weight": 0.2,
        "points": 20,
        "note": "West Papua, ID"
      }
    ],
    "provenance": "api",
    "updated_at": "2026-06-29T07:53:34.659Z",
    "status": "signal",
    "created_at": "2026-06-29T07:53:34.659Z"
  },
  {
    "source": "inaturalist",
    "external_id": "376460601",
    "title": "Emperor Breams",
    "url": "https://www.inaturalist.org/observations/376460601",
    "observed_on": "2026-05-10",
    "location_label": "West Papua, ID",
    "taxon_hint": "Lethrinidae",
    "summary": "Observasi iNaturalist berstatus needs-ID, baru teridentifikasi sampai tingkat family (Lethrinidae).",
    "score": 82,
    "signals": [
      {
        "key": "mystery",
        "label": "Kedalaman misteri (belum teridentifikasi)",
        "value": 0.6,
        "weight": 0.45,
        "points": 27,
        "note": "Teridentifikasi sampai tingkat family"
      },
      {
        "key": "recency",
        "label": "Kebaruan",
        "value": 0.99,
        "weight": 0.35,
        "points": 35,
        "note": "Tertanggal 2026-05-10"
      },
      {
        "key": "locatable",
        "label": "Dapat dilacak (ada lokasi)",
        "value": 1,
        "weight": 0.2,
        "points": 20,
        "note": "West Papua, ID"
      }
    ],
    "provenance": "api",
    "updated_at": "2026-06-29T07:53:34.659Z",
    "status": "signal",
    "created_at": "2026-06-29T07:53:34.659Z"
  },
  {
    "source": "inaturalist",
    "external_id": "376471388",
    "title": "True Crickets and Allies",
    "url": "https://www.inaturalist.org/observations/376471388",
    "observed_on": "2025-01-01",
    "location_label": "2PRJ+W85, Batu Ampar, Kec. Kemuning, Kabupaten Indragiri Hilir, Riau 29274, Indonesia",
    "taxon_hint": "Grylloidea",
    "summary": "Observasi iNaturalist berstatus needs-ID, baru teridentifikasi sampai tingkat superfamily (Grylloidea).",
    "score": 79,
    "signals": [
      {
        "key": "mystery",
        "label": "Kedalaman misteri (belum teridentifikasi)",
        "value": 0.65,
        "weight": 0.45,
        "points": 29,
        "note": "Teridentifikasi sampai tingkat superfamily"
      },
      {
        "key": "recency",
        "label": "Kebaruan",
        "value": 0.85,
        "weight": 0.35,
        "points": 30,
        "note": "Tertanggal 2025-01-01"
      },
      {
        "key": "locatable",
        "label": "Dapat dilacak (ada lokasi)",
        "value": 1,
        "weight": 0.2,
        "points": 20,
        "note": "2PRJ+W85, Batu Ampar, Kec. Kemuning, Kabupaten Indragiri Hilir, Riau 29274, Indonesia"
      }
    ],
    "provenance": "api",
    "updated_at": "2026-06-29T07:53:34.659Z",
    "status": "signal",
    "created_at": "2026-06-29T07:53:34.659Z"
  },
  {
    "source": "inaturalist",
    "external_id": "376471028",
    "title": "True Crickets and Allies",
    "url": "https://www.inaturalist.org/observations/376471028",
    "observed_on": "2025-01-01",
    "location_label": "2PVJ+458, Batuampar, Selensen, Kec. Kemuning, Kabupaten Indragiri Hilir, Riau 29274, Indonesia",
    "taxon_hint": "Grylloidea",
    "summary": "Observasi iNaturalist berstatus needs-ID, baru teridentifikasi sampai tingkat superfamily (Grylloidea).",
    "score": 79,
    "signals": [
      {
        "key": "mystery",
        "label": "Kedalaman misteri (belum teridentifikasi)",
        "value": 0.65,
        "weight": 0.45,
        "points": 29,
        "note": "Teridentifikasi sampai tingkat superfamily"
      },
      {
        "key": "recency",
        "label": "Kebaruan",
        "value": 0.85,
        "weight": 0.35,
        "points": 30,
        "note": "Tertanggal 2025-01-01"
      },
      {
        "key": "locatable",
        "label": "Dapat dilacak (ada lokasi)",
        "value": 1,
        "weight": 0.2,
        "points": 20,
        "note": "2PVJ+458, Batuampar, Selensen, Kec. Kemuning, Kabupaten Indragiri Hilir, Riau 29274, Indonesia"
      }
    ],
    "provenance": "api",
    "updated_at": "2026-06-29T07:53:34.659Z",
    "status": "signal",
    "created_at": "2026-06-29T07:53:34.659Z"
  },
  {
    "source": "xeno-canto",
    "external_id": "sample-xc-1",
    "title": "CONTOH: rekaman burung tak teridentifikasi (Xeno-canto)",
    "url": "https://xeno-canto.org/explore?query=cnt%3Aindonesia",
    "observed_on": null,
    "location_label": "Indonesia",
    "taxon_hint": null,
    "summary": "Contoh kartu sinyal Xeno-canto. Pantauan live rekaman tak teridentifikasi membutuhkan XENOCANTO_API_KEY (API v3).",
    "score": 76,
    "signals": [
      {
        "key": "mystery",
        "label": "Kedalaman misteri (belum teridentifikasi)",
        "value": 1,
        "weight": 0.45,
        "points": 45,
        "note": "Teridentifikasi sampai tingkat tidak ada"
      },
      {
        "key": "recency",
        "label": "Kebaruan",
        "value": 0.3,
        "weight": 0.35,
        "points": 11,
        "note": "Tidak ada tanggal"
      },
      {
        "key": "locatable",
        "label": "Dapat dilacak (ada lokasi)",
        "value": 1,
        "weight": 0.2,
        "points": 20,
        "note": "Indonesia"
      }
    ],
    "provenance": "sample",
    "updated_at": "2026-06-29T07:53:34.659Z",
    "status": "signal",
    "created_at": "2026-06-29T07:53:34.659Z"
  },
  {
    "source": "youtube",
    "external_id": "sample-yt-1",
    "title": "CONTOH: video satwa tak dikenal (YouTube)",
    "url": "https://www.youtube.com/results?search_query=hewan+aneh+indonesia",
    "observed_on": null,
    "location_label": "Indonesia",
    "taxon_hint": null,
    "summary": "Contoh kartu sinyal YouTube. Pantauan live klip satwa tak dikenal membutuhkan YOUTUBE_API_KEY (YouTube Data API v3).",
    "score": 76,
    "signals": [
      {
        "key": "mystery",
        "label": "Kedalaman misteri (belum teridentifikasi)",
        "value": 1,
        "weight": 0.45,
        "points": 45,
        "note": "Teridentifikasi sampai tingkat tidak ada"
      },
      {
        "key": "recency",
        "label": "Kebaruan",
        "value": 0.3,
        "weight": 0.35,
        "points": 11,
        "note": "Tidak ada tanggal"
      },
      {
        "key": "locatable",
        "label": "Dapat dilacak (ada lokasi)",
        "value": 1,
        "weight": 0.2,
        "points": 20,
        "note": "Indonesia"
      }
    ],
    "provenance": "sample",
    "updated_at": "2026-06-29T07:53:34.659Z",
    "status": "signal",
    "created_at": "2026-06-29T07:53:34.659Z"
  },
  {
    "source": "inaturalist",
    "external_id": "376473100",
    "title": "Nembrotha",
    "url": "https://www.inaturalist.org/observations/376473100",
    "observed_on": "2026-06-22",
    "location_label": "Bali Barat, ID-BA-BL, ID-BA, ID",
    "taxon_hint": "Nembrotha",
    "summary": "Observasi iNaturalist berstatus needs-ID, baru teridentifikasi sampai tingkat genus (Nembrotha).",
    "score": 73,
    "signals": [
      {
        "key": "mystery",
        "label": "Kedalaman misteri (belum teridentifikasi)",
        "value": 0.4,
        "weight": 0.45,
        "points": 18,
        "note": "Teridentifikasi sampai tingkat genus"
      },
      {
        "key": "recency",
        "label": "Kebaruan",
        "value": 1,
        "weight": 0.35,
        "points": 35,
        "note": "Tertanggal 2026-06-22"
      },
      {
        "key": "locatable",
        "label": "Dapat dilacak (ada lokasi)",
        "value": 1,
        "weight": 0.2,
        "points": 20,
        "note": "Bali Barat, ID-BA-BL, ID-BA, ID"
      }
    ],
    "provenance": "api",
    "updated_at": "2026-06-29T07:53:34.659Z",
    "status": "signal",
    "created_at": "2026-06-29T07:53:34.659Z"
  },
  {
    "source": "inaturalist",
    "external_id": "376468872",
    "title": "Asian Box Turtles",
    "url": "https://www.inaturalist.org/observations/376468872",
    "observed_on": "2026-06-28",
    "location_label": "GCPV+MQP, Kelurahan Kampung Dalam, Senapelan, Pekanbaru City, Riau 28155, Indonesia",
    "taxon_hint": "Cuora",
    "summary": "Observasi iNaturalist berstatus needs-ID, baru teridentifikasi sampai tingkat genus (Cuora).",
    "score": 73,
    "signals": [
      {
        "key": "mystery",
        "label": "Kedalaman misteri (belum teridentifikasi)",
        "value": 0.4,
        "weight": 0.45,
        "points": 18,
        "note": "Teridentifikasi sampai tingkat genus"
      },
      {
        "key": "recency",
        "label": "Kebaruan",
        "value": 1,
        "weight": 0.35,
        "points": 35,
        "note": "Tertanggal 2026-06-28"
      },
      {
        "key": "locatable",
        "label": "Dapat dilacak (ada lokasi)",
        "value": 1,
        "weight": 0.2,
        "points": 20,
        "note": "GCPV+MQP, Kelurahan Kampung Dalam, Senapelan, Pekanbaru City, Riau 28155, Indonesia"
      }
    ],
    "provenance": "api",
    "updated_at": "2026-06-29T07:53:34.659Z",
    "status": "signal",
    "created_at": "2026-06-29T07:53:34.659Z"
  },
  {
    "source": "inaturalist",
    "external_id": "376464738",
    "title": "Spiny Ants",
    "url": "https://www.inaturalist.org/observations/376464738",
    "observed_on": "2026-06-29",
    "location_label": "Gianyar, Bali, ID",
    "taxon_hint": "Polyrhachis",
    "summary": "Observasi iNaturalist berstatus needs-ID, baru teridentifikasi sampai tingkat genus (Polyrhachis).",
    "score": 73,
    "signals": [
      {
        "key": "mystery",
        "label": "Kedalaman misteri (belum teridentifikasi)",
        "value": 0.4,
        "weight": 0.45,
        "points": 18,
        "note": "Teridentifikasi sampai tingkat genus"
      },
      {
        "key": "recency",
        "label": "Kebaruan",
        "value": 1,
        "weight": 0.35,
        "points": 35,
        "note": "Tertanggal 2026-06-29"
      },
      {
        "key": "locatable",
        "label": "Dapat dilacak (ada lokasi)",
        "value": 1,
        "weight": 0.2,
        "points": 20,
        "note": "Gianyar, Bali, ID"
      }
    ],
    "provenance": "api",
    "updated_at": "2026-06-29T07:53:34.659Z",
    "status": "signal",
    "created_at": "2026-06-29T07:53:34.659Z"
  },
  {
    "source": "inaturalist",
    "external_id": "376461572",
    "title": "Baron and Duke Butterflies",
    "url": "https://www.inaturalist.org/observations/376461572",
    "observed_on": "2026-06-29",
    "location_label": "XPVF+4F9, Letung, Jemaja, Kepulauan Anambas Regency, Riau Islands 29792, Indonesia",
    "taxon_hint": "Euthalia",
    "summary": "Observasi iNaturalist berstatus needs-ID, baru teridentifikasi sampai tingkat genus (Euthalia).",
    "score": 73,
    "signals": [
      {
        "key": "mystery",
        "label": "Kedalaman misteri (belum teridentifikasi)",
        "value": 0.4,
        "weight": 0.45,
        "points": 18,
        "note": "Teridentifikasi sampai tingkat genus"
      },
      {
        "key": "recency",
        "label": "Kebaruan",
        "value": 1,
        "weight": 0.35,
        "points": 35,
        "note": "Tertanggal 2026-06-29"
      },
      {
        "key": "locatable",
        "label": "Dapat dilacak (ada lokasi)",
        "value": 1,
        "weight": 0.2,
        "points": 20,
        "note": "XPVF+4F9, Letung, Jemaja, Kepulauan Anambas Regency, Riau Islands 29792, Indonesia"
      }
    ],
    "provenance": "api",
    "updated_at": "2026-06-29T07:53:34.659Z",
    "status": "signal",
    "created_at": "2026-06-29T07:53:34.659Z"
  },
  {
    "source": "inaturalist",
    "external_id": "376460460",
    "title": "Giant Asian Mantises",
    "url": "https://www.inaturalist.org/observations/376460460",
    "observed_on": "2026-06-28",
    "location_label": "Gianyar, Bali, ID",
    "taxon_hint": "Hierodula",
    "summary": "Observasi iNaturalist berstatus needs-ID, baru teridentifikasi sampai tingkat genus (Hierodula).",
    "score": 73,
    "signals": [
      {
        "key": "mystery",
        "label": "Kedalaman misteri (belum teridentifikasi)",
        "value": 0.4,
        "weight": 0.45,
        "points": 18,
        "note": "Teridentifikasi sampai tingkat genus"
      },
      {
        "key": "recency",
        "label": "Kebaruan",
        "value": 1,
        "weight": 0.35,
        "points": 35,
        "note": "Tertanggal 2026-06-28"
      },
      {
        "key": "locatable",
        "label": "Dapat dilacak (ada lokasi)",
        "value": 1,
        "weight": 0.2,
        "points": 20,
        "note": "Gianyar, Bali, ID"
      }
    ],
    "provenance": "api",
    "updated_at": "2026-06-29T07:53:34.659Z",
    "status": "signal",
    "created_at": "2026-06-29T07:53:34.659Z"
  },
  {
    "source": "inaturalist",
    "external_id": "376470616",
    "title": "Teleogryllus",
    "url": "https://www.inaturalist.org/observations/376470616",
    "observed_on": "2025-01-01",
    "location_label": "2PVJ+458, Batuampar, Selensen, Kec. Kemuning, Kabupaten Indragiri Hilir, Riau 29274, Indonesia",
    "taxon_hint": "Teleogryllus",
    "summary": "Observasi iNaturalist berstatus needs-ID, baru teridentifikasi sampai tingkat genus (Teleogryllus).",
    "score": 68,
    "signals": [
      {
        "key": "mystery",
        "label": "Kedalaman misteri (belum teridentifikasi)",
        "value": 0.4,
        "weight": 0.45,
        "points": 18,
        "note": "Teridentifikasi sampai tingkat genus"
      },
      {
        "key": "recency",
        "label": "Kebaruan",
        "value": 0.85,
        "weight": 0.35,
        "points": 30,
        "note": "Tertanggal 2025-01-01"
      },
      {
        "key": "locatable",
        "label": "Dapat dilacak (ada lokasi)",
        "value": 1,
        "weight": 0.2,
        "points": 20,
        "note": "2PVJ+458, Batuampar, Selensen, Kec. Kemuning, Kabupaten Indragiri Hilir, Riau 29274, Indonesia"
      }
    ],
    "provenance": "api",
    "updated_at": "2026-06-29T07:53:34.659Z",
    "status": "signal",
    "created_at": "2026-06-29T07:53:34.659Z"
  },
  {
    "source": "inaturalist",
    "external_id": "376458163",
    "title": "Hard-headed Crickets",
    "url": "https://www.inaturalist.org/observations/376458163",
    "observed_on": "2025-01-01",
    "location_label": "Batu Ampar, Kec. Kemuning, Kabupaten Indragiri Hilir, Riau, Indonesia",
    "taxon_hint": "Loxoblemmus",
    "summary": "Observasi iNaturalist berstatus needs-ID, baru teridentifikasi sampai tingkat genus (Loxoblemmus).",
    "score": 68,
    "signals": [
      {
        "key": "mystery",
        "label": "Kedalaman misteri (belum teridentifikasi)",
        "value": 0.4,
        "weight": 0.45,
        "points": 18,
        "note": "Teridentifikasi sampai tingkat genus"
      },
      {
        "key": "recency",
        "label": "Kebaruan",
        "value": 0.85,
        "weight": 0.35,
        "points": 30,
        "note": "Tertanggal 2025-01-01"
      },
      {
        "key": "locatable",
        "label": "Dapat dilacak (ada lokasi)",
        "value": 1,
        "weight": 0.2,
        "points": 20,
        "note": "Batu Ampar, Kec. Kemuning, Kabupaten Indragiri Hilir, Riau, Indonesia"
      }
    ],
    "provenance": "api",
    "updated_at": "2026-06-29T07:53:34.659Z",
    "status": "signal",
    "created_at": "2026-06-29T07:53:34.659Z"
  }
];
