// AUTO-GENERATED by `node scripts/lab/build-leads.mjs --emit-sample`.
// Do not edit by hand. A snapshot of REAL harvested data (GBIF + iNaturalist
// live, IUCN curated public categories), used as the /lab dashboard fallback
// when the lab_leads table is empty. Surfaced in the UI as CONTOH, never as
// reviewed leads. Regenerate after re-harvesting.
import type { LabLeadRow } from "@/lib/lab/leads";

export const SAMPLE_LEAD_ROWS: LabLeadRow[] = [
  {
    "taxon_name": "Panthera tigris sondaica",
    "taxon_rank": "subspecies",
    "common_name": "Harimau Jawa",
    "iucn_status": "EX",
    "last_record_year": 2026,
    "score": null,
    "signals": [
      {
        "key": "gbif_gap",
        "label": "Jeda sejak rekaman GBIF terakhir",
        "value": 0,
        "note": "0 tahun (terakhir 2026)"
      },
      {
        "key": "gbif_scarcity",
        "label": "Kelangkaan rekaman GBIF",
        "value": 0.51,
        "note": "88 okurensi global, 69 di Indonesia"
      },
      {
        "key": "inat_recent_obs",
        "label": "Observasi riset iNaturalist (menurunkan prioritas)",
        "value": 1,
        "note": "46 observasi riset, terbaru 2026 (Indonesia 45)"
      },
      {
        "key": "iucn_status",
        "label": "Status ancaman IUCN",
        "value": 1,
        "note": "EX (kurasi)"
      }
    ],
    "sources": [
      {
        "label": "GBIF",
        "url": "https://www.gbif.org/occurrence/search?taxon_key=5219422"
      },
      {
        "label": "iNaturalist",
        "url": "https://www.inaturalist.org/observations?taxon_id=130799&quality_grade=research"
      },
      {
        "label": "IUCN (kurasi)",
        "url": "https://www.iucnredlist.org/search?query=Panthera%20tigris%20sondaica"
      }
    ],
    "status": "lead",
    "notes": null,
    "created_at": "2026-06-30T04:13:51.529Z",
    "updated_at": "2026-06-30T04:13:51.529Z"
  },
  {
    "taxon_name": "Malacocincla perspicillata",
    "taxon_rank": "species",
    "common_name": "Black-browed babbler",
    "iucn_status": "DD",
    "last_record_year": 2024,
    "score": null,
    "signals": [
      {
        "key": "gbif_gap",
        "label": "Jeda sejak rekaman GBIF terakhir",
        "value": 0.04,
        "note": "2 tahun (terakhir 2024)"
      },
      {
        "key": "gbif_scarcity",
        "label": "Kelangkaan rekaman GBIF",
        "value": 0.71,
        "note": "14 okurensi global, 8 di Indonesia"
      },
      {
        "key": "inat_recent_obs",
        "label": "Observasi riset iNaturalist (menurunkan prioritas)",
        "value": 0.93,
        "note": "9 observasi riset, terbaru 2024 (Indonesia 6)"
      },
      {
        "key": "iucn_status",
        "label": "Status ancaman IUCN",
        "value": 0.65,
        "note": "DD (kurasi)"
      }
    ],
    "sources": [
      {
        "label": "GBIF",
        "url": "https://www.gbif.org/occurrence/search?taxon_key=2493402"
      },
      {
        "label": "iNaturalist",
        "url": "https://www.inaturalist.org/observations?taxon_id=15145&quality_grade=research"
      },
      {
        "label": "IUCN (kurasi)",
        "url": "https://www.iucnredlist.org/search?query=Malacocincla%20perspicillata"
      }
    ],
    "status": "lead",
    "notes": null,
    "created_at": "2026-06-30T04:13:51.529Z",
    "updated_at": "2026-06-30T04:13:51.529Z"
  },
  {
    "taxon_name": "Eutrichomyias rowleyi",
    "taxon_rank": "species",
    "common_name": "Seriwang Sangihe",
    "iucn_status": "CR",
    "last_record_year": 2025,
    "score": null,
    "signals": [
      {
        "key": "gbif_gap",
        "label": "Jeda sejak rekaman GBIF terakhir",
        "value": 0.02,
        "note": "1 tahun (terakhir 2025)"
      },
      {
        "key": "gbif_scarcity",
        "label": "Kelangkaan rekaman GBIF",
        "value": 0.66,
        "note": "21 okurensi global, 20 di Indonesia"
      },
      {
        "key": "inat_recent_obs",
        "label": "Observasi riset iNaturalist (menurunkan prioritas)",
        "value": 0.9,
        "note": "12 observasi riset, terbaru 2023 (Indonesia 12)"
      },
      {
        "key": "iucn_status",
        "label": "Status ancaman IUCN",
        "value": 0.9,
        "note": "CR (kurasi)"
      }
    ],
    "sources": [
      {
        "label": "GBIF",
        "url": "https://www.gbif.org/occurrence/search?taxon_key=2486697"
      },
      {
        "label": "iNaturalist",
        "url": "https://www.inaturalist.org/observations?taxon_id=8604&quality_grade=research"
      },
      {
        "label": "IUCN (kurasi)",
        "url": "https://www.iucnredlist.org/search?query=Eutrichomyias%20rowleyi"
      }
    ],
    "status": "lead",
    "notes": null,
    "created_at": "2026-06-30T04:13:51.529Z",
    "updated_at": "2026-06-30T04:13:51.529Z"
  },
  {
    "taxon_name": "Megachile pluto",
    "taxon_rank": "species",
    "common_name": "Lebah raksasa Wallace",
    "iucn_status": "VU",
    "last_record_year": 2025,
    "score": null,
    "signals": [
      {
        "key": "gbif_gap",
        "label": "Jeda sejak rekaman GBIF terakhir",
        "value": 0.02,
        "note": "1 tahun (terakhir 2025)"
      },
      {
        "key": "gbif_scarcity",
        "label": "Kelangkaan rekaman GBIF",
        "value": 0.72,
        "note": "12 okurensi global, 7 di Indonesia"
      },
      {
        "key": "inat_recent_obs",
        "label": "Observasi riset iNaturalist (menurunkan prioritas)",
        "value": 0.97,
        "note": "2 observasi riset, terbaru 2025 (Indonesia 2)"
      },
      {
        "key": "iucn_status",
        "label": "Status ancaman IUCN",
        "value": 0.5,
        "note": "VU (kurasi)"
      }
    ],
    "sources": [
      {
        "label": "GBIF",
        "url": "https://www.gbif.org/occurrence/search?taxon_key=1336561"
      },
      {
        "label": "iNaturalist",
        "url": "https://www.inaturalist.org/observations?taxon_id=97243&quality_grade=research"
      },
      {
        "label": "IUCN (kurasi)",
        "url": "https://www.iucnredlist.org/search?query=Megachile%20pluto"
      }
    ],
    "status": "lead",
    "notes": null,
    "created_at": "2026-06-30T04:13:51.529Z",
    "updated_at": "2026-06-30T04:13:51.529Z"
  },
  {
    "taxon_name": "Latimeria menadoensis",
    "taxon_rank": "species",
    "common_name": "Coelacanth Sulawesi",
    "iucn_status": "VU",
    "last_record_year": 2013,
    "score": null,
    "signals": [
      {
        "key": "gbif_gap",
        "label": "Jeda sejak rekaman GBIF terakhir",
        "value": 0.26,
        "note": "13 tahun (terakhir 2013)"
      },
      {
        "key": "gbif_scarcity",
        "label": "Kelangkaan rekaman GBIF",
        "value": 0.69,
        "note": "16 okurensi global, 5 di Indonesia"
      },
      {
        "key": "inat_recent_obs",
        "label": "Observasi riset iNaturalist (menurunkan prioritas)",
        "value": 0,
        "note": "Tidak ada observasi riset"
      },
      {
        "key": "iucn_status",
        "label": "Status ancaman IUCN",
        "value": 0.5,
        "note": "VU (kurasi)"
      }
    ],
    "sources": [
      {
        "label": "GBIF",
        "url": "https://www.gbif.org/occurrence/search?taxon_key=2441276"
      },
      {
        "label": "iNaturalist",
        "url": "https://www.inaturalist.org/observations?taxon_id=104110&quality_grade=research"
      },
      {
        "label": "IUCN (kurasi)",
        "url": "https://www.iucnredlist.org/search?query=Latimeria%20menadoensis"
      }
    ],
    "status": "lead",
    "notes": null,
    "created_at": "2026-06-30T04:13:51.529Z",
    "updated_at": "2026-06-30T04:13:51.529Z"
  },
  {
    "taxon_name": "Nepenthes pitopangii",
    "taxon_rank": "species",
    "common_name": "Kantong semar Sulawesi",
    "iucn_status": "VU",
    "last_record_year": 2026,
    "score": null,
    "signals": [
      {
        "key": "gbif_gap",
        "label": "Jeda sejak rekaman GBIF terakhir",
        "value": 0,
        "note": "0 tahun (terakhir 2026)"
      },
      {
        "key": "gbif_scarcity",
        "label": "Kelangkaan rekaman GBIF",
        "value": 0.71,
        "note": "13 okurensi global, 12 di Indonesia"
      },
      {
        "key": "inat_recent_obs",
        "label": "Observasi riset iNaturalist (menurunkan prioritas)",
        "value": 1,
        "note": "14 observasi riset, terbaru 2026 (Indonesia 13)"
      },
      {
        "key": "iucn_status",
        "label": "Status ancaman IUCN",
        "value": 0.5,
        "note": "VU (kurasi)"
      }
    ],
    "sources": [
      {
        "label": "GBIF",
        "url": "https://www.gbif.org/occurrence/search?taxon_key=4930501"
      },
      {
        "label": "iNaturalist",
        "url": "https://www.inaturalist.org/observations?taxon_id=441243&quality_grade=research"
      },
      {
        "label": "IUCN (kurasi)",
        "url": "https://www.iucnredlist.org/search?query=Nepenthes%20pitopangii"
      }
    ],
    "status": "lead",
    "notes": null,
    "created_at": "2026-06-30T04:13:51.529Z",
    "updated_at": "2026-06-30T04:13:51.529Z"
  },
  {
    "taxon_name": "Rhinoceros sondaicus",
    "taxon_rank": "species",
    "common_name": "Badak Jawa",
    "iucn_status": "CR",
    "last_record_year": 2023,
    "score": null,
    "signals": [
      {
        "key": "gbif_gap",
        "label": "Jeda sejak rekaman GBIF terakhir",
        "value": 0.06,
        "note": "3 tahun (terakhir 2023)"
      },
      {
        "key": "gbif_scarcity",
        "label": "Kelangkaan rekaman GBIF",
        "value": 0.35,
        "note": "392 okurensi global, 333 di Indonesia"
      },
      {
        "key": "inat_recent_obs",
        "label": "Observasi riset iNaturalist (menurunkan prioritas)",
        "value": 0.87,
        "note": "7 observasi riset, terbaru 2022 (Indonesia 7)"
      },
      {
        "key": "iucn_status",
        "label": "Status ancaman IUCN",
        "value": 0.9,
        "note": "CR (kurasi)"
      }
    ],
    "sources": [
      {
        "label": "GBIF",
        "url": "https://www.gbif.org/occurrence/search?taxon_key=5220112"
      },
      {
        "label": "iNaturalist",
        "url": "https://www.inaturalist.org/observations?taxon_id=43346&quality_grade=research"
      },
      {
        "label": "IUCN (kurasi)",
        "url": "https://www.iucnredlist.org/search?query=Rhinoceros%20sondaicus"
      }
    ],
    "status": "lead",
    "notes": null,
    "created_at": "2026-06-30T04:13:51.529Z",
    "updated_at": "2026-06-30T04:13:51.529Z"
  },
  {
    "taxon_name": "Orcaella brevirostris",
    "taxon_rank": "species",
    "common_name": "Pesut Mahakam",
    "iucn_status": "EN",
    "last_record_year": 2026,
    "score": null,
    "signals": [
      {
        "key": "gbif_gap",
        "label": "Jeda sejak rekaman GBIF terakhir",
        "value": 0,
        "note": "0 tahun (terakhir 2026)"
      },
      {
        "key": "gbif_scarcity",
        "label": "Kelangkaan rekaman GBIF",
        "value": 0.26,
        "note": "918 okurensi global, 48 di Indonesia"
      },
      {
        "key": "inat_recent_obs",
        "label": "Observasi riset iNaturalist (menurunkan prioritas)",
        "value": 1,
        "note": "285 observasi riset, terbaru 2026 (Indonesia 4)"
      },
      {
        "key": "iucn_status",
        "label": "Status ancaman IUCN",
        "value": 0.7,
        "note": "EN (kurasi)"
      }
    ],
    "sources": [
      {
        "label": "GBIF",
        "url": "https://www.gbif.org/occurrence/search?taxon_key=2440460"
      },
      {
        "label": "iNaturalist",
        "url": "https://www.inaturalist.org/observations?taxon_id=41519&quality_grade=research"
      },
      {
        "label": "IUCN (kurasi)",
        "url": "https://www.iucnredlist.org/search?query=Orcaella%20brevirostris"
      }
    ],
    "status": "lead",
    "notes": null,
    "created_at": "2026-06-30T04:13:51.529Z",
    "updated_at": "2026-06-30T04:13:51.529Z"
  },
  {
    "taxon_name": "Zaglossus attenboroughi",
    "taxon_rank": "species",
    "common_name": "Echidna paruh panjang Attenborough",
    "iucn_status": "CR",
    "last_record_year": 1961,
    "score": null,
    "signals": [
      {
        "key": "gbif_gap",
        "label": "Jeda sejak rekaman GBIF terakhir",
        "value": 1,
        "note": "65 tahun (terakhir 1961)"
      },
      {
        "key": "gbif_scarcity",
        "label": "Kelangkaan rekaman GBIF",
        "value": 0.83,
        "note": "4 okurensi global, 3 di Indonesia"
      },
      {
        "key": "inat_recent_obs",
        "label": "Observasi riset iNaturalist (menurunkan prioritas)",
        "value": 0,
        "note": "Tidak ada observasi riset"
      },
      {
        "key": "iucn_status",
        "label": "Status ancaman IUCN",
        "value": 0.9,
        "note": "CR (kurasi)"
      }
    ],
    "sources": [
      {
        "label": "GBIF",
        "url": "https://www.gbif.org/occurrence/search?taxon_key=2433390"
      },
      {
        "label": "iNaturalist",
        "url": "https://www.inaturalist.org/observations?taxon_id=43247&quality_grade=research"
      },
      {
        "label": "IUCN (kurasi)",
        "url": "https://www.iucnredlist.org/search?query=Zaglossus%20attenboroughi"
      }
    ],
    "status": "lead",
    "notes": null,
    "created_at": "2026-06-30T04:13:51.529Z",
    "updated_at": "2026-06-30T04:13:51.529Z"
  },
  {
    "taxon_name": "Cyornis ruckii",
    "taxon_rank": "species",
    "common_name": "Sikatan Rueck",
    "iucn_status": "EN",
    "last_record_year": null,
    "score": null,
    "signals": [
      {
        "key": "gbif_gap",
        "label": "Jeda sejak rekaman GBIF terakhir",
        "value": 1,
        "note": "Tidak ada rekaman GBIF berkala"
      },
      {
        "key": "gbif_scarcity",
        "label": "Kelangkaan rekaman GBIF",
        "value": 1,
        "note": "0 okurensi global, 0 di Indonesia"
      },
      {
        "key": "inat_recent_obs",
        "label": "Observasi riset iNaturalist (menurunkan prioritas)",
        "value": 0,
        "note": "Tidak ada observasi riset"
      },
      {
        "key": "iucn_status",
        "label": "Status ancaman IUCN",
        "value": 0.7,
        "note": "EN (kurasi)"
      }
    ],
    "sources": [
      {
        "label": "GBIF",
        "url": "https://www.gbif.org/occurrence/search?taxon_key=2492441"
      },
      {
        "label": "iNaturalist",
        "url": "https://www.inaturalist.org/observations?taxon_id=12859&quality_grade=research"
      },
      {
        "label": "IUCN (kurasi)",
        "url": "https://www.iucnredlist.org/search?query=Cyornis%20ruckii"
      }
    ],
    "status": "lead",
    "notes": null,
    "created_at": "2026-06-30T04:13:51.529Z",
    "updated_at": "2026-06-30T04:13:51.529Z"
  },
  {
    "taxon_name": "Varanus zugorum",
    "taxon_rank": "species",
    "common_name": "Biawak Zug",
    "iucn_status": "DD",
    "last_record_year": 1980,
    "score": null,
    "signals": [
      {
        "key": "gbif_gap",
        "label": "Jeda sejak rekaman GBIF terakhir",
        "value": 0.92,
        "note": "46 tahun (terakhir 1980)"
      },
      {
        "key": "gbif_scarcity",
        "label": "Kelangkaan rekaman GBIF",
        "value": 0.92,
        "note": "1 okurensi global, 1 di Indonesia"
      },
      {
        "key": "inat_recent_obs",
        "label": "Observasi riset iNaturalist (menurunkan prioritas)",
        "value": 0,
        "note": "Tidak ada observasi riset"
      },
      {
        "key": "iucn_status",
        "label": "Status ancaman IUCN",
        "value": 0.65,
        "note": "DD (kurasi)"
      }
    ],
    "sources": [
      {
        "label": "GBIF",
        "url": "https://www.gbif.org/occurrence/search?taxon_key=2470837"
      },
      {
        "label": "iNaturalist",
        "url": "https://www.inaturalist.org/observations?taxon_id=39431&quality_grade=research"
      },
      {
        "label": "IUCN (kurasi)",
        "url": "https://www.iucnredlist.org/search?query=Varanus%20zugorum"
      }
    ],
    "status": "lead",
    "notes": null,
    "created_at": "2026-06-30T04:13:51.529Z",
    "updated_at": "2026-06-30T04:13:51.529Z"
  },
  {
    "taxon_name": "Gallirallus sharpei",
    "taxon_rank": "species",
    "common_name": "Mandar Sharpe",
    "iucn_status": null,
    "last_record_year": null,
    "score": null,
    "signals": [
      {
        "key": "gbif_gap",
        "label": "Jeda sejak rekaman GBIF terakhir",
        "value": 1,
        "note": "Tidak ada rekaman GBIF berkala"
      },
      {
        "key": "gbif_scarcity",
        "label": "Kelangkaan rekaman GBIF",
        "value": 1,
        "note": "0 okurensi global, 0 di Indonesia"
      },
      {
        "key": "inat_recent_obs",
        "label": "Observasi riset iNaturalist (menurunkan prioritas)",
        "value": 0,
        "note": "Tidak ada observasi riset"
      }
    ],
    "sources": [
      {
        "label": "GBIF",
        "url": "https://www.gbif.org/occurrence/search?taxon_key=2474543"
      },
      {
        "label": "iNaturalist",
        "url": "https://www.inaturalist.org/taxa/search?q=Gallirallus%20sharpei"
      },
      {
        "label": "IUCN (kurasi)",
        "url": "https://www.iucnredlist.org/search?query=Gallirallus%20sharpei"
      }
    ],
    "status": "lead",
    "notes": null,
    "created_at": "2026-06-30T04:13:51.529Z",
    "updated_at": "2026-06-30T04:13:51.529Z"
  }
];
