import { NextResponse } from "next/server";
import { loadGraphData, graphIsStale } from "@/lib/graph/generate";
import type { GraphData, NodeType } from "@/lib/graph/types";

export const dynamic = "force-dynamic";

const NODE_TYPES: NodeType[] = ["article", "source", "topic", "series", "vertical"];

/** Keep only edges whose endpoints both survive the node filter. */
function pruneEdges(graph: GraphData, keptIds: Set<string>): GraphData["edges"] {
  return graph.edges.filter((e) => keptIds.has(e.source) && keptIds.has(e.target));
}

/**
 * GET /api/graph
 *   ?type=article|source|topic|series|vertical  -> nodes of that type (+ their edges)
 *   ?vertical=alam|sejarah|investigasi          -> that pillar's articles and neighbours
 * Serves the cached graph (public/graph-data.json), generated by the sync /
 * build pipeline. Cache-Control max-age=3600.
 */
export async function GET(request: Request) {
  const graph = loadGraphData();
  const url = new URL(request.url);
  const type = url.searchParams.get("type");
  const vertical = url.searchParams.get("vertical");

  let nodes = graph.nodes;

  if (type && NODE_TYPES.includes(type as NodeType)) {
    nodes = nodes.filter((n) => n.type === type);
  }

  if (vertical) {
    const articleIds = new Set(
      graph.nodes.filter((n) => n.type === "article" && n.vertical === vertical).map((n) => n.id),
    );
    // neighbours of those articles, via edges
    const keep = new Set(articleIds);
    keep.add(`vertical:${vertical}`);
    for (const e of graph.edges) {
      if (articleIds.has(e.source)) keep.add(e.target);
      if (articleIds.has(e.target)) keep.add(e.source);
    }
    nodes = nodes.filter((n) => keep.has(n.id));
  }

  const keptIds = new Set(nodes.map((n) => n.id));
  const edges = pruneEdges(graph, keptIds);

  return NextResponse.json(
    {
      nodes,
      edges,
      meta: { ...graph.meta, returnedNodes: nodes.length, returnedEdges: edges.length, stale: graphIsStale(graph) },
    },
    { headers: { "Cache-Control": "public, max-age=3600" } },
  );
}
