#!/usr/bin/env node
/**
 * build-signals (Lab, Step 3.5). Combines the three ghost-signal dumps, scores
 * each with a transparent notability heuristic, and either upserts into
 * public.ghost_signals (service role), prints (--dry-run), or snapshots a
 * committed fixture (--emit-sample -> lib/lab/sample-signals.ts).
 *
 * The score is a PRIORITIZATION heuristic, never a probability that a notable
 * species is present. Every point is explained in `signals`.
 */
import fs from "node:fs";
import path from "node:path";
import { readDump, getServiceClient, ROOT, rel } from "../_shared.mjs";
import { harvestInat } from "./harvest-inat-needsid.mjs";
import { harvestXenocanto } from "./harvest-xenocanto.mjs";
import { harvestYoutube } from "./harvest-youtube.mjs";

const DRY = process.argv.includes("--dry-run");
const EMIT_SAMPLE = process.argv.includes("--emit-sample");
const SAMPLE_FILE = path.join(ROOT, "lib", "lab", "sample-signals.ts");
const NOW = Date.now();
const clamp = (v) => Math.max(0, Math.min(1, v));
const round2 = (v) => Number(v.toFixed(2));

const RANK_DEPTH = {
  "tidak ada": 1.0,
  kingdom: 0.85, phylum: 0.85, subphylum: 0.85, class: 0.8, subclass: 0.8,
  order: 0.8, suborder: 0.8, superfamily: 0.65, family: 0.6, subfamily: 0.6,
  tribe: 0.6, genus: 0.4, subgenus: 0.4, complex: 0.5,
};

const W = { mystery: 0.45, recency: 0.35, locatable: 0.2 };

function scoreSignal(s) {
  const mystery = RANK_DEPTH[(s.taxonRank || "tidak ada").toLowerCase()] ?? 0.3;
  let recency = 0.3; // neutral when undated
  if (s.observedOn) {
    const ageDays = (NOW - Date.parse(s.observedOn)) / 86400000;
    if (Number.isFinite(ageDays)) recency = clamp(1 - ageDays / 3650); // 10yr horizon
  }
  const locatable = s.locationLabel ? 1 : 0;
  const breakdown = [
    {
      key: "mystery",
      label: "Kedalaman misteri (belum teridentifikasi)",
      value: round2(mystery),
      weight: W.mystery,
      points: Math.round(W.mystery * mystery * 100),
      note: `Teridentifikasi sampai tingkat ${s.taxonRank || "tidak ada"}`,
    },
    {
      key: "recency",
      label: "Kebaruan",
      value: round2(recency),
      weight: W.recency,
      points: Math.round(W.recency * recency * 100),
      note: s.observedOn ? `Tertanggal ${s.observedOn}` : "Tidak ada tanggal",
    },
    {
      key: "locatable",
      label: "Dapat dilacak (ada lokasi)",
      value: locatable,
      weight: W.locatable,
      points: Math.round(W.locatable * locatable * 100),
      note: s.locationLabel ? s.locationLabel : "Tanpa label lokasi",
    },
  ];
  const score = Math.max(0, Math.min(100, breakdown.reduce((a, c) => a + c.points, 0)));
  return { score, breakdown };
}

function toRow(s) {
  const { score, breakdown } = scoreSignal(s);
  return {
    source: s.source,
    external_id: s.externalId,
    title: s.title,
    url: s.url,
    observed_on: s.observedOn || null,
    location_label: s.locationLabel || null,
    taxon_hint: s.taxonHint || null,
    summary: s.summary || null,
    score,
    signals: breakdown,
    provenance: s.provenance || "api",
    updated_at: new Date().toISOString(),
  };
}

async function collect() {
  // Prefer fresh dumps if present; otherwise harvest live (iNat real, others
  // fall back to sample inside their modules).
  const inat = readDump("ghost-inat", null) || (await harvestInat());
  const xc = readDump("ghost-xenocanto", null) || (await harvestXenocanto());
  const yt = readDump("ghost-youtube", null) || (await harvestYoutube());
  return [...inat, ...xc, ...yt];
}

async function main() {
  const raw = await collect();
  const rows = raw.map(toRow).sort((a, b) => b.score - a.score);
  console.log(`Built ${rows.length} ghost signals.\n`);
  for (const r of rows.slice(0, 12)) {
    console.log(`  [${String(r.score).padStart(3)}] ${r.source.padEnd(11)} ${r.title.slice(0, 48)}`);
  }

  if (EMIT_SAMPLE) {
    const now = new Date().toISOString();
    const sample = rows.map((r) => ({ ...r, status: "signal", created_at: now, updated_at: now }));
    const body =
      "// AUTO-GENERATED by `node scripts/lab/ghost/build-signals.mjs --emit-sample`.\n" +
      "// Do not edit by hand. Snapshot of real iNaturalist needs-ID ghost signals\n" +
      "// (+ labeled CONTOH samples for the key-gated Xeno-canto/YouTube sources).\n" +
      "// Used as the /lab/signals fallback when ghost_signals is empty. Internal,\n" +
      "// unverified anomalies, never public.\n" +
      'import type { GhostSignalRow } from "@/lib/lab/ghost";\n\n' +
      `export const SAMPLE_GHOST_SIGNALS: GhostSignalRow[] = ${JSON.stringify(sample, null, 2)};\n`;
    fs.mkdirSync(path.dirname(SAMPLE_FILE), { recursive: true });
    fs.writeFileSync(SAMPLE_FILE, body);
    console.log(`\n--emit-sample: wrote ${rel(SAMPLE_FILE)} (${sample.length} signals).`);
    return;
  }
  if (DRY) {
    console.log("\n--dry-run: nothing written.");
    return;
  }

  const sb = await getServiceClient();
  if (!sb) process.exit(1);
  const { error } = await sb
    .from("ghost_signals")
    .upsert(rows, { onConflict: "source,external_id", ignoreDuplicates: false });
  if (error) {
    console.error("\nUpsert failed:", error.message);
    process.exit(1);
  }
  console.log(`\nUpserted ${rows.length} ghost signals (status/notes preserved).`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
