import type { RawPublication } from "@/lib/types";
import { publicationsBatch1 } from "./publications/batch-1";
import { publicationsBatch2 } from "./publications/batch-2";
import { publicationsBatch3 } from "./publications/batch-3";

/**
 * Master list of Jurnal publication records (real external journals, reports,
 * datasets, and archives). Covers are attached at load time from pub-covers.json.
 * Batches are generated by the Fase 7 knowledge pipeline and registered here.
 */
export const publications: RawPublication[] = [
  ...publicationsBatch1,
  ...publicationsBatch2,
  ...publicationsBatch3,
];
